// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("ATypes")]
public partial class Atype
{
    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(100)]
    public string Description { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
    [Key]
    [Column("MArks", TypeName = "money")]
    public decimal? Marks { get; set; }
}