// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("awards")]
public partial class Award
{
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Course { get; set; }
    [Key]
    [Column("CFrom", TypeName = "smalldatetime")]
    public DateTime? Cfrom { get; set; }

    [Column("CTo", TypeName = "smalldatetime")]
    public DateTime? Cto { get; set; }

    [Column("ELevel")]
    [StringLength(200)]
    public string Elevel { get; set; }

    [Column("Award")]
    [StringLength(200)]
    public string Award1 { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [Column("CAward", TypeName = "money")]
    public decimal? Caward { get; set; }

    [Column("AType")]
    [StringLength(50)]
    public string Atype { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}