// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("CompanyAssetIssue")]
public partial class CompanyAssetIssue
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("Employee_ID")]
    public int? EmployeeId { get; set; }

    [StringLength(50)]
    public string AssetCode { get; set; }

    [StringLength(100)]
    public string Comments { get; set; }
}