// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("cstructure")]
public partial class Cstructure
{
    [Key]
    [Column("cstructure_id")]
    public int CstructureId { get; set; }

    [Column("SCode")]
    [StringLength(20)]
    public string Scode { get; set; }

    [Column("LCode")]
    [StringLength(200)]
    public string Lcode { get; set; }

    [Column("PCode")]
    [StringLength(20)]
    public string Pcode { get; set; }

    public int? MyLevel { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(50)]
    public string TelNo { get; set; }

    [StringLength(50)]
    public string Fax { get; set; }

    [StringLength(200)]
    public string Email { get; set; }

    [StringLength(50)]
    public string PinNo { get; set; }

    [StringLength(50)]
    public string NhifNo { get; set; }

    [StringLength(50)]
    public string NssfNo { get; set; }

    [StringLength(50)]
    public string LascNo { get; set; }

    [Column("MPerc")]
    public int? Mperc { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    public bool? Loaded { get; set; }
}