// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("c_table_details")]
public partial class CTableDetail
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("table_type")]
    [StringLength(255)]
    public string TableType { get; set; }

    [Column("table_code")]
    [StringLength(255)]
    public string TableCode { get; set; }

    [Column("table_code_description")]
    [StringLength(255)]
    public string TableCodeDescription { get; set; }

    [Column("table_code_value")]
    [StringLength(255)]
    public string TableCodeValue { get; set; }
}