// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]

[Table("CUser")]
public partial class Cuser
{
    [Key]
    [Column("UName")]
    [StringLength(50)]
    public string Uname { get; set; }

    [Column("PWord")]
    [StringLength(50)]
    public string Pword { get; set; }

    public int? NoTrial { get; set; }

    [Column("GNo")]
    [StringLength(50)]
    public string Gno { get; set; }

    public bool? All { get; set; }

    public bool? Some { get; set; }

    public bool? Read { get; set; }

    public bool? Exc { get; set; }

    public bool? Admin { get; set; }

    [StringLength(50)]
    public string Excc { get; set; }

    [StringLength(50)]
    public string Subsystem { get; set; }
}