// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("dCaseRating")]
public partial class DCaseRating
{
    [Key]
    [Column("RatingID")]
    public int RatingId { get; set; }

    [StringLength(14)]
    [Unicode(false)]
    public string RatingCode { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string RatingDesc { get; set; }
   
    [Column("RScale")]
    public byte Rscale { get; set; }

    [Required]
    [Column("RComments")]
    [StringLength(200)]
    [Unicode(false)]
    public string Rcomments { get; set; }
}