// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("EditLetter")]
public partial class EditLetter
{
    [Key]
    [Column("LType")]
    [StringLength(20)]
    public string Ltype { get; set; }

    [Column("myLetter", TypeName = "ntext")]
    public string MyLetter { get; set; }
}