// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("education")]
public partial class Education
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [Column("IName")]
    [StringLength(200)]
    public string Iname { get; set; }

    [StringLength(200)]
    public string Level { get; set; }

    [StringLength(200)]
    public string Award { get; set; }

    [StringLength(200)]
    public string Course { get; set; }

    [StringLength(5)]
    public string From { get; set; }

    [StringLength(5)]
    public string To { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}