// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("empaccts")]
public partial class Empacct
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(50)]
    public string AcctNo { get; set; }

    [StringLength(200)]
    public string Bank { get; set; }

    [StringLength(5)]
    public string Main { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}