// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("EmpDet")]
public partial class EmpDet
{
    [StringLength(255)]
    public string Empcode { get; set; }

    [StringLength(255)]
    public string Name { get; set; }
    [Key]
    [Column("ACCOUNT NAME")]
    [StringLength(255)]
    public string AccountName { get; set; }

    [Column("BANKNAME")]
    [StringLength(255)]
    public string Bankname { get; set; }

    [Column("BANKBRANCHNAME")]
    [StringLength(255)]
    public string Bankbranchname { get; set; }

    [Column("BRANCHCODE")]
    [StringLength(255)]
    public string Branchcode { get; set; }

    [Column("ACCOUNTNO")]
    [StringLength(255)]
    public string Accountno { get; set; }
}