// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("Experience")]
public partial class Experience
{
    [Key]
    [Column("PCode")]
    [StringLength(20)]
    public string Pcode { get; set; }

    [Column("DCode")]
    [StringLength(20)]
    public string Dcode { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("myValue")]
    [StringLength(200)]
    public string MyValue { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}