// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("GroupCat")]
public partial class GroupCat
{
    [Column("GNo")]
    [StringLength(20)]
    public string Gno { get; set; }

    [Column("ECategory")]
    [StringLength(50)]
    public string Ecategory { get; set; }

    [StringLength(20)]
    public string MyAccess { get; set; }
}