// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class GroupModule
{
    [Column("GNo")]
    [StringLength(20)]
    public string Gno { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(200)]
    public string MyRight { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Subsystem { get; set; }
}