// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("kin")]
public partial class Kin
{
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string SurName { get; set; }

    [StringLength(200)]
    public string OtherNames { get; set; }

    [Column("IDNo")]
    [StringLength(200)]
    public string Idno { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PassportNo { get; set; }

    [StringLength(50)]
    public string AlienNo { get; set; }

    [StringLength(20)]
    public string Relation { get; set; }

    [Column("DOB")]
    [StringLength(10)]
    public string Dob { get; set; }

    [StringLength(200)]
    public string Occupation { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [Column("HTelNo")]
    [StringLength(50)]
    public string HtelNo { get; set; }

    [StringLength(50)]
    public string OffTelNo { get; set; }

    [Column("MNo")]
    [StringLength(50)]
    public string Mno { get; set; }

    [Column("EMail")]
    [StringLength(200)]
    public string Email { get; set; }

    [StringLength(5)]
    public string Signed { get; set; }

    [Column("SDate", TypeName = "smalldatetime")]
    public DateTime? Sdate { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}