// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class LevelType
{
    [Column("LCode")]
    [StringLength(20)]
    public string Lcode { get; set; }

    [Column("myLevel")]
    [StringLength(200)]
    public string MyLevel { get; set; }

    [StringLength(250)]
    public string Comments { get; set; }
}