// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("LGroups")]
public partial class Lgroup
{
    [Column("NCode")]
    [StringLength(50)]
    public string Ncode { get; set; }

    [Column("ACode")]
    [StringLength(50)]
    public string Acode { get; set; }

    [Column("MGroup")]
    [StringLength(50)]
    public string Mgroup { get; set; }

    [Column("PGroups")]
    [StringLength(50)]
    public string Pgroups { get; set; }
}