// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("LPeriod")]
public partial class Lperiod
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Period { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [Column(TypeName = "money")]
    public decimal? Marks { get; set; }
}