// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("LSCategory")]
public partial class Lscategory
{
    [Column("ACode")]
    [StringLength(20)]
    public string Acode { get; set; }

    [Column("CCode")]
    [StringLength(20)]
    public string Ccode { get; set; }

    [Column("SCode")]
    [StringLength(20)]
    public string Scode { get; set; }

    [StringLength(5)]
    public string Heading { get; set; }

    [StringLength(50)]
    public string Type { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}