// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("names")]
public partial class Name
{
    [StringLength(255)]
    [Unicode(false)]
    public string MemberNo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string LastName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string OtherNames { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string FullName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Designation { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string JobGroup { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Sex { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string MaritalStatus { get; set; }

    [Column("NSSFNo")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nssfno { get; set; }

    [Column("NHIFNO")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nhifno { get; set; }

    [Column("IDNumber")]
    [StringLength(255)]
    [Unicode(false)]
    public string Idnumber { get; set; }

    [Column("PINNumber")]
    [StringLength(255)]
    [Unicode(false)]
    public string Pinnumber { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string BirthDate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EmpDate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string QuitDate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string EndPrd { get; set; }

    [Column("M_days_Hrs")]
    [StringLength(255)]
    [Unicode(false)]
    public string MDaysHrs { get; set; }

    [Column("Hr_PayRate")]
    [StringLength(255)]
    [Unicode(false)]
    public string HrPayRate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string AnnIncrement { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string IncrementDate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string IncrMonth { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string MaxSalary { get; set; }

    [Column("MPR_Original")]
    [StringLength(255)]
    [Unicode(false)]
    public string MprOriginal { get; set; }

    [Column("MPR_Revised")]
    [StringLength(255)]
    [Unicode(false)]
    public string MprRevised { get; set; }

    [Column("MPR_CF")]
    [StringLength(255)]
    [Unicode(false)]
    public string MprCf { get; set; }

    [Column("MPR_OrigDate")]
    [StringLength(255)]
    [Unicode(false)]
    public string MprOrigDate { get; set; }

    [Column("MPR_RevDate")]
    [StringLength(255)]
    [Unicode(false)]
    public string MprRevDate { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Station { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Dept { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string BankCode { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string AccountNo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Pensionable { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PensionLimit { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Housed { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string HouseCost { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Suspended { get; set; }

    [Column("Suspend_bk")]
    [StringLength(255)]
    [Unicode(false)]
    public string SuspendBk { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string UnionMember { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string OwnerOccupier { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TaxFree { get; set; }

    [Column("HOSP")]
    [StringLength(255)]
    [Unicode(false)]
    public string Hosp { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PrevEmpName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PrevEmpAddress { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NewEmpName { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string NewEmpAddr { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string BasicPay { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string GrossPay { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Deductions { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TaxableAmount { get; set; }

    [Column("revTaxableAmt")]
    [StringLength(255)]
    [Unicode(false)]
    public string RevTaxableAmt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TaxableCashPay { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TaxableBenefit { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Tax { get; set; }

    [Column("PAYEAmt")]
    [StringLength(255)]
    [Unicode(false)]
    public string Payeamt { get; set; }

    [Column("NSSFAmt")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nssfamt { get; set; }

    [Column("NHIFAmt")]
    [StringLength(255)]
    [Unicode(false)]
    public string Nhifamt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PensionAmt { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string PayFor { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Period { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string TimeStamp { get; set; }
}