// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class NewNeed
{
    public int Code { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("NBy")]
    [StringLength(200)]
    public string Nby { get; set; }

    [StringLength(200)]
    public string Intend { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}