// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("NProcess")]
public partial class Nprocess
{
    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("UGroup")]
    [StringLength(50)]
    public string Ugroup { get; set; }

    [Column("PRights")]
    [StringLength(5)]
    public string Prights { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}