// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("PApproval")]
public partial class Papproval
{
    [StringLength(50)]
    public string PositionCode { get; set; }

    [StringLength(20)]
    public string EmployeeCode { get; set; }

    [StringLength(5)]
    public string Approved { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}