// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("pdCompanyCodesCat")]
public partial class PdCompanyCodesCat
{
    [Required]
    [Column("code")]
    [StringLength(10)]
    public string Code { get; set; }

    [Required]
    [Column("description")]
    [StringLength(200)]
    public string Description { get; set; }
}