// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("pdSalaryChange")]
public partial class PdSalaryChange
{
    [Column("id")]
    public int Id { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }

    [Column("changedate", TypeName = "datetime")]
    public DateTime? Changedate { get; set; }

    [StringLength(20)]
    public string IncreaseType { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? BasicPay { get; set; }

    [Column("HAllow", TypeName = "numeric(18, 0)")]
    public decimal? Hallow { get; set; }

    [Column("TAllow", TypeName = "numeric(18, 0)")]
    public decimal? Tallow { get; set; }

    [Column("LAllow", TypeName = "numeric(18, 0)")]
    public decimal? Lallow { get; set; }

    [Column("OAllow", TypeName = "numeric(18, 0)")]
    public decimal? Oallow { get; set; }

    [Column("pBP", TypeName = "numeric(18, 0)")]
    public decimal? PBp { get; set; }

    [Column("pHA", TypeName = "numeric(18, 0)")]
    public decimal? PHa { get; set; }

    [Column("pTA", TypeName = "numeric(18, 0)")]
    public decimal? PTa { get; set; }

    [Column("pLA", TypeName = "numeric(18, 0)")]
    public decimal? PLa { get; set; }

    [Column("pOA", TypeName = "numeric(18, 0)")]
    public decimal? POa { get; set; }
}