// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

public partial class Position
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("code")]
    [StringLength(10)]
    [Unicode(false)]
    public string Code { get; set; }

    [Column("positionName")]
    [StringLength(50)]
    public string PositionName { get; set; }

    public bool? Approved { get; set; }

    [Column("comments")]
    [StringLength(500)]
    public string Comments { get; set; }

    public double? Dailyrate { get; set; }

    [Column(TypeName = "money")]
    public decimal? BasicPay { get; set; }

    [Column(TypeName = "money")]
    public decimal? TravellingAllowance { get; set; }

    [Column(TypeName = "money")]
    public decimal? HouseAllownce { get; set; }
}