// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class PositionRequirement
{
    [Column("PositionRequirementsID")]
    public int PositionRequirementsId { get; set; }

    [StringLength(200)]
    public string PositionRequirementsDescription { get; set; }

    [StringLength(200)]
    public string PositionRequirementsComments { get; set; }
}