// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class PostCategory
{
    [Column("DCode")]
    [StringLength(20)]
    public string Dcode { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }
}