// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class Qualification
{
    [Column("DCode")]
    [StringLength(50)]
    public string Dcode { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [Column("myQualification")]
    [StringLength(200)]
    public string MyQualification { get; set; }

    [Column("myReq")]
    public int? MyReq { get; set; }
}