// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("QualifOnlySearch")]
public partial class QualifOnlySearch
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [Column("myQualification")]
    [StringLength(200)]
    public string MyQualification { get; set; }
}