// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("Ref")]
public partial class Ref
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(250)]
    public string Names { get; set; }

    [Column("IDNo")]
    [StringLength(200)]
    public string Idno { get; set; }

    [Column("MNo")]
    [StringLength(50)]
    public string Mno { get; set; }

    [Column("EMail")]
    [StringLength(200)]
    public string Email { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}