// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblAllTasks")]
public partial class TblAllTask
{
    [Key]
    [Column("MODULE_ID")]
    public int ModuleId { get; set; }

    [Column("MODULE_NAME")]
    [StringLength(250)]
    public string ModuleName { get; set; }
}