// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblAssignedRights")]
public partial class TblAssignedRight
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("GROUP_ID")]
    [StringLength(50)]
    public string GroupId { get; set; }

    [Required]
    [Column("MODULE_ID")]
    [StringLength(50)]
    public string ModuleId { get; set; }

    [Column("MODULE_NAME")]
    [StringLength(50)]
    public string ModuleName { get; set; }

    [Column("ASSIGNED_RIGHTS")]
    [StringLength(50)]
    public string AssignedRights { get; set; }

    [Column("DONEBY")]
    [StringLength(50)]
    public string Doneby { get; set; }

    [Column("DATEDONE", TypeName = "smalldatetime")]
    public DateTime? Datedone { get; set; }

    [Required]
    [StringLength(50)]
    public string SubSystem { get; set; }
}