// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblBankBranch")]
public partial class TblBankBranch
{
    [Key]
    [Column("BANKBRANCH_ID")]
    public int BankbranchId { get; set; }

    [Column("BANK_ID")]
    [StringLength(50)]
    public string BankId { get; set; }

    [Column("BANKBRANCH_CODE")]
    [StringLength(50)]
    public string BankbranchCode { get; set; }

    [Column("BANK_NAME")]
    [StringLength(250)]
    public string BankName { get; set; }

    [Column("BANKBRANCH_NAME")]
    [StringLength(50)]
    public string BankbranchName { get; set; }

    [StringLength(250)]
    public string Comments { get; set; }

    [Column("BankId")]
    public int? BankId1 { get; set; }

    public int? BranchId { get; set; }
}