// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCurrency")]
public partial class TblCurrency
{
    [Key]
    [Column("CURRENCY_ID")]
    public int CurrencyId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("CURRENCY_CODE")]
    [StringLength(50)]
    public string CurrencyCode { get; set; }

    [Column("CURRENCY_NAME")]
    [StringLength(50)]
    public string CurrencyName { get; set; }

    [Column("CURRENCY_CONVRATE")]
    public double? CurrencyConvrate { get; set; }

    [Column("CURRENCY_BASE")]
    public bool CurrencyBase { get; set; }
}