// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCasualPaymentPeriods")]
public partial class TblCasualPaymentPeriod
{
    [Key]
    [Column("PERIOD_ID")]
    public int PeriodId { get; set; }

    [Column("CRITERIA_ID")]
    public int? CriteriaId { get; set; }

    [Column("START_DATE")]
    public int? StartDate { get; set; }

    [Column("START_MONTH")]
    public int? StartMonth { get; set; }

    [Column("START_YEAR")]
    public int? StartYear { get; set; }

    [Column("END_DATE")]
    public int? EndDate { get; set; }

    [Column("END_MONTH")]
    public int? EndMonth { get; set; }

    [Column("END_YEAR")]
    public int? EndYear { get; set; }
}