// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCostCenter")]
public partial class TblCostCenter
{
    [Key]
    [Column("COSTCENTER_ID")]
    public int CostcenterId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("CODE")]
    [StringLength(50)]
    public string Code { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(100)]
    public string Description { get; set; }

    [Column("CSTRUCTURE_ID")]
    public int? CstructureId { get; set; }
}