// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblCooperative")]
public partial class TblCooperative
{
    [Column("COOP_ID")]
    public int CoopId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("COOPERATIVE_CODE")]
    [StringLength(50)]
    public string CooperativeCode { get; set; }

    [Column("COOPERATIVE_NAME")]
    [StringLength(250)]
    public string CooperativeName { get; set; }

    [Column("CONTACT_PERSON")]
    [StringLength(50)]
    public string ContactPerson { get; set; }

    [Column("BANKBRANCH_ID")]
    public int? BankbranchId { get; set; }

    [Column("ACCOUNT_NUMBER")]
    [StringLength(50)]
    public string AccountNumber { get; set; }

    [Column("ADDRESS", TypeName = "ntext")]
    public string Address { get; set; }

    [Column("PO_BOX")]
    [StringLength(50)]
    public string PoBox { get; set; }

    [Column("POSTAL_CODE")]
    [StringLength(50)]
    public string PostalCode { get; set; }

    [Column("CITY")]
    [StringLength(50)]
    public string City { get; set; }

    [Column("COUNTRY")]
    [StringLength(50)]
    public string Country { get; set; }

    [Column("TEL1")]
    [StringLength(50)]
    public string Tel1 { get; set; }

    [Column("TEL2")]
    [StringLength(50)]
    public string Tel2 { get; set; }

    [Column("TEL3")]
    [StringLength(50)]
    public string Tel3 { get; set; }

    [Column("TEL4")]
    [StringLength(50)]
    public string Tel4 { get; set; }

    [Column("FAX_NUMBER")]
    [StringLength(50)]
    public string FaxNumber { get; set; }

    [Column("EMAIL")]
    [StringLength(50)]
    public string Email { get; set; }

    [Column("WEB_URL")]
    [StringLength(50)]
    public string WebUrl { get; set; }

    [Column("COMMENTS", TypeName = "ntext")]
    public string Comments { get; set; }
}