// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblDefineContributionBenefit")]
public partial class TblDefineContributionBenefit
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PERCENTAGE_OF_TAXABLE", TypeName = "decimal(18, 0)")]
    public decimal? PercentageOfTaxable { get; set; }

    [Column("FIXED_LIMIT", TypeName = "money")]
    public decimal? FixedLimit { get; set; }

    [Column("ROUNDING")]
    public double? Rounding { get; set; }
}