// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblEmployeeDefinedBenefits")]
public partial class TblEmployeeDefinedBenefit
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("BENEFIT_ID")]
    public int? BenefitId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }
}