// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeRemuneration")]
public partial class TblEmployeeRemuneration
{
    [Key]
    [Column("EMPRENUM_ID")]
    public int EmprenumId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("REMUNERATION_ID")]
    public int? RemunerationId { get; set; }

    [Column("ISAMOUNT")]
    public bool? Isamount { get; set; }

    [Column("AMOUNT_VALUE", TypeName = "money")]
    public decimal? AmountValue { get; set; }

    [Column("FORMULA")]
    [StringLength(50)]
    public string Formula { get; set; }
}