// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeePayrollPeriods")]
public partial class TblEmployeePayrollPeriod
{
    [Key]
    [Column("Process_ID")]
    public int ProcessId { get; set; }

    [Column("Employee_ID")]
    public int EmployeeId { get; set; }

    [Column("Period_Month")]
    public int PeriodMonth { get; set; }

    [Column("Period_Year")]
    public int PeriodYear { get; set; }
}