// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeAllowance")]
public partial class TblEmployeeAllowance
{
    [Key]
    [Column("EMPLOYEEALLOWANCE_ID")]
    public int EmployeeallowanceId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("ALLOWANCE_ID")]
    public int? AllowanceId { get; set; }

    [Column("AMOUNT")]
    [StringLength(50)]
    public string Amount { get; set; }

    [Column("BASIC_PAY")]
    public bool BasicPay { get; set; }

    [Column("MONTHLY")]
    public bool Monthly { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }
}