// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeBonus")]
public partial class TblEmployeeBonu
{
    [Key]
    [Column("EMPBONUS_ID")]
    public int EmpbonusId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("BONUSDETAIL_ID")]
    public int? BonusdetailId { get; set; }

    [Column("RATE_BASED")]
    public bool RateBased { get; set; }

    [Column("BONUS_VALUE")]
    public double? BonusValue { get; set; }

    [Column("PERIOD")]
    public int? Period { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("PROCESSED")]
    public bool Processed { get; set; }
}