// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[PrimaryKey("EmployeeId", "CostcenterId")]
[Table("tblEmployeeCostCenter")]
public partial class TblEmployeeCostCenter
{
    
    [Column("EMPLOYEECOSTCENTER_ID")]
    public int EmployeecostcenterId { get; set; }

    [Key]
    [Column("EMPLOYEE_ID")]
    public int EmployeeId { get; set; }

    
    [Column("COSTCENTER_ID")]
    public int CostcenterId { get; set; }

    [Column("RATE")]
    [StringLength(50)]
    public string Rate { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("PERCENTAGE")]
    public double? Percentage { get; set; }
}