// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblGroupModule")]
public partial class TblGroupModule
{
    [Column("MODULE_ID")]
    public int ModuleId { get; set; }

    [Column("GROUP_ID")]
    public int? GroupId { get; set; }

    [Column("ALLOW_VIEW")]
    public bool AllowView { get; set; }

    [Column("ALLOW_INSERT")]
    public bool AllowInsert { get; set; }

    [Column("ALLOW_UPDATE")]
    public bool AllowUpdate { get; set; }

    [Column("ALLOW_DELETE")]
    public bool AllowDelete { get; set; }
}