// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblHeadOfSubDepartment")]
public partial class TblHeadOfSubDepartment
{
    [Column("HOSD_ID")]
    public int HosdId { get; set; }

    [Column("SDEPARTMENT_ID")]
    public int? SdepartmentId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("DATE_CHANGED", TypeName = "smalldatetime")]
    public DateTime? DateChanged { get; set; }
}