// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblHoliday")]
public partial class TblHoliday
{
    [Column("HOLIDAY_ID")]
    public int HolidayId { get; set; }

    [Column("HOLIDAY_DATE", TypeName = "smalldatetime")]
    public DateTime? HolidayDate { get; set; }

    [Column("HOLIDAY_DAY")]
    public int? HolidayDay { get; set; }

    [Column("HOLIDAY_MONTH")]
    public int? HolidayMonth { get; set; }

    [Column("HOLIDAY_NAME", TypeName = "ntext")]
    public string HolidayName { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }
}