// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblJVReport")]
public partial class TblJvreport
{
    [StringLength(50)]
    public string AccountNo { get; set; }

    [Column("CostCenter_Id")]
    public int? CostCenterId { get; set; }

    [StringLength(50)]
    public string AccountDescription { get; set; }

    [Column("Amount_Debit", TypeName = "money")]
    public decimal? AmountDebit { get; set; }

    [Column("Amount_Credit", TypeName = "money")]
    public decimal? AmountCredit { get; set; }
}