// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblLoanSchedule")]
public partial class TblLoanSchedule
{
    [Key]
    [Column("SCHEDULE_ID")]
    public int ScheduleId { get; set; }

    [Column("EMPLOYEELOAN_ID")]
    public int EmployeeloanId { get; set; }

    [Column("LOAN_AMOUNT", TypeName = "money")]
    public decimal? LoanAmount { get; set; }

    [Column("RECOVERY_AMOUNT", TypeName = "money")]
    public decimal? RecoveryAmount { get; set; }

    [Column("INTEREST", TypeName = "money")]
    public decimal? Interest { get; set; }

    [Column("AMOUNT_DUE", TypeName = "money")]
    public decimal? AmountDue { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }
}