// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblMotorCars")]
public partial class TblMotorCar
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("RANGE_CODE")]
    [StringLength(50)]
    public string RangeCode { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(50)]
    public string Description { get; set; }

    [Column("PRESCRIBED_RATE", TypeName = "money")]
    public decimal? PrescribedRate { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }
}