// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblNSSF")]
public partial class TblNssf
{
    [Key]
    [Column("NSSF_ID")]
    public int NssfId { get; set; }

    [Column("BASICPAY")]
    public bool? Basicpay { get; set; }

    [Column("BASIC_PERCENTAGE", TypeName = "decimal(18, 0)")]
    public decimal? BasicPercentage { get; set; }

    [Column("GROSS_PERCENTAGE", TypeName = "decimal(18, 0)")]
    public decimal? GrossPercentage { get; set; }

    [Column("EMPLOYEE_MAXIMUM")]
    public double? EmployeeMaximum { get; set; }

    [Column("EMPLOYER_FACTOR")]
    public double? EmployerFactor { get; set; }

    [Column("NSSF_ROUNDING", TypeName = "decimal(18, 0)")]
    public decimal? NssfRounding { get; set; }

    [Column("DEFINE_CONTRIBUTION")]
    public bool? DefineContribution { get; set; }

    [Column("VOLUNTARY_DESCRIPTION")]
    [StringLength(100)]
    public string VoluntaryDescription { get; set; }

    [Column("VOLUNTARY_PAYROLLCODEID")]
    public int? VoluntaryPayrollcodeid { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }
}