// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblNHIF")]
public partial class TblNhif
{
    [Key]
    [Column("NHIF_ID")]
    public int NhifId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("NHIF_TIER")]
    public double? NhifTier { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }
}