// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblNSSF_SFI")]
public partial class TblNssfSfi
{
    [Column("NSSFSFI_BODY", TypeName = "ntext")]
    public string NssfsfiBody { get; set; }
}