// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblOverWrite")]
public partial class TblOverWrite
{
    [Key]
    [Column("TRANSID")]
    public int Transid { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("NSSF_OVERWRITE", TypeName = "money")]
    public decimal? NssfOverwrite { get; set; }

    [Column("NHIF_OVERWRITE", TypeName = "money")]
    public decimal? NhifOverwrite { get; set; }

    [Column("PAYE_OVERWRITE", TypeName = "money")]
    public decimal? PayeOverwrite { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }
}