// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPeriodDetail")]
public partial class TblPeriodDetail
{
    [Key]
    [Column("PERIODDETAIL_ID")]
    public int PerioddetailId { get; set; }

    [Column("PERIOD_ID")]
    public int? PeriodId { get; set; }

    [Column("PERIODDETAIL_NUMBER")]
    public int? PerioddetailNumber { get; set; }

    [Column("PERIODDETAIL_NAME")]
    [StringLength(50)]
    public string PerioddetailName { get; set; }
}