// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPension")]
public partial class TblPension
{
    [Column("PENSION_ID")]
    public int PensionId { get; set; }

    [Key]
    [Column("PAYROLLCODE_ID")]
    public int PayrollcodeId { get; set; }

    [Required]
    [Column("PENSION_CODE")]
    [StringLength(50)]
    public string PensionCode { get; set; }

    [Required]
    [Column("PENSION_NAME")]
    [StringLength(50)]
    public string PensionName { get; set; }

    [Required]
    [Column("COMMENTS", TypeName = "ntext")]
    public string Comments { get; set; }

    [Column("BASEDON")]
    public int Basedon { get; set; }

    [Column("PENSION_RATE")]
    public bool PensionRate { get; set; }

    [Column("EMPLOYER")]
    public double Employer { get; set; }

    [Column("EMPLOYEE")]
    public double Employee { get; set; }

    [Column("EXEMPT_EMPLOYEE_NSSF")]
    public bool ExemptEmployeeNssf { get; set; }

    [Column("DEDUCT_NSSF_FROM")]
    public bool DeductNssfFrom { get; set; }
}