// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPaypoint")]
public partial class TblPaypoint
{
    [Key]
    [Column("PAYPOINT_ID")]
    public int PaypointId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("PAYPOINT_CODE")]
    [StringLength(50)]
    public string PaypointCode { get; set; }

    [Column("PAYPOINT_NAME")]
    [StringLength(250)]
    public string PaypointName { get; set; }

    [Column("PIN_NUMBER")]
    [StringLength(50)]
    public string PinNumber { get; set; }

    [Column("NSSF_NUMBER")]
    [StringLength(50)]
    public string NssfNumber { get; set; }

    [Column("NHIF_NUMBER")]
    [StringLength(50)]
    public string NhifNumber { get; set; }

    [Column("ADDRESS", TypeName = "ntext")]
    public string Address { get; set; }

    [Column("PO_BOX")]
    [StringLength(50)]
    public string PoBox { get; set; }

    [Column("POSTAL_CODE")]
    [StringLength(50)]
    public string PostalCode { get; set; }

    [Column("CITY")]
    [StringLength(50)]
    public string City { get; set; }

    [Column("COUNTRY")]
    [StringLength(50)]
    public string Country { get; set; }

    [Column("TEL1")]
    [StringLength(50)]
    public string Tel1 { get; set; }

    [Column("TEL2")]
    [StringLength(50)]
    public string Tel2 { get; set; }

    [Column("TEL3")]
    [StringLength(50)]
    public string Tel3 { get; set; }

    [Column("TEL4")]
    [StringLength(50)]
    public string Tel4 { get; set; }

    [Column("FAX_NUMBER")]
    [StringLength(50)]
    public string FaxNumber { get; set; }

    [Column("EMAIL")]
    [StringLength(50)]
    public string Email { get; set; }

    [Column("WEB_URL")]
    [StringLength(250)]
    public string WebUrl { get; set; }

    [Column("COMMENTS", TypeName = "ntext")]
    public string Comments { get; set; }

    [Column("BLOCKED")]
    public bool Blocked { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }
}