// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPolicy")]
public partial class TblPolicy
{
    [Key]
    [Column("POLICY_ID")]
    public int PolicyId { get; set; }

    [Column("INS_ID")]
    public int? InsId { get; set; }

    [Column("POLICY_CODE")]
    [StringLength(50)]
    public string PolicyCode { get; set; }

    [Column("POLICY_NAME")]
    [StringLength(50)]
    public string PolicyName { get; set; }

    [Column("POLICY_LIFE")]
    public bool PolicyLife { get; set; }
}