// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblRemuneration")]
public partial class TblRemuneration
{
    [Key]
    [Column("Remuneration_ID")]
    public int RemunerationId { get; set; }

    [Column("REMUNERATION_CODE")]
    [StringLength(50)]
    public string RemunerationCode { get; set; }

    [Column("REMUNERATION_NAME")]
    [StringLength(50)]
    public string RemunerationName { get; set; }

    [Column("REMUNERATION_COMMENTS")]
    [StringLength(100)]
    public string RemunerationComments { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }
}