// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblRangeBenefits")]
public partial class TblRangeBenefit
{
    public int RangeBenefitId { get; set; }

    public int PayrollcodeRangeId { get; set; }

    public int BenefitId { get; set; }
}