// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblServants")]
public partial class TblServant
{
    [Key]
    [Column("Servants_Id")]
    public long ServantsId { get; set; }

    [Column("House_Servant_Rural", TypeName = "money")]
    public decimal? HouseServantRural { get; set; }

    [Column("House_Servant_Urban", TypeName = "money")]
    public decimal? HouseServantUrban { get; set; }

    [Column("Watchman_Day_Urban", TypeName = "money")]
    public decimal? WatchmanDayUrban { get; set; }

    [Column("Watchman_Day_Rural", TypeName = "money")]
    public decimal? WatchmanDayRural { get; set; }

    [Column("Watchman_Night_Rural", TypeName = "money")]
    public decimal? WatchmanNightRural { get; set; }

    [Column("Watchman_Night_Urban", TypeName = "money")]
    public decimal? WatchmanNightUrban { get; set; }

    [Column("Ayah_Rural", TypeName = "money")]
    public decimal? AyahRural { get; set; }

    [Column("Ayah_Urban", TypeName = "money")]
    public decimal? AyahUrban { get; set; }

    [Column("Gardener_Urban", TypeName = "money")]
    public decimal? GardenerUrban { get; set; }

    [Column("Gardener_Rural", TypeName = "money")]
    public decimal? GardenerRural { get; set; }

    [Column("Monthly_Benefit_Threshold", TypeName = "money")]
    public decimal? MonthlyBenefitThreshold { get; set; }

    [Column("Show_Detailed_Benefit")]
    public bool? ShowDetailedBenefit { get; set; }
}