// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblSendPayslips")]
public partial class TblSendPayslip
{
    public int EmailId { get; set; }

    public int? EmployeeId { get; set; }

    public int? Status { get; set; }

    public int? PeriodMonth { get; set; }

    public int? PeriodYear { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ModifiedBy { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Supflag { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SuprvisedBy { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? SuprvisedOn { get; set; }
}