// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblSystemPayrollCodes")]
public partial class TblSystemPayrollCode
{
    [Key]
    [Column("SystemCode_ID")]
    public int SystemCodeId { get; set; }

    [Column("System_Payroll_Code")]
    [StringLength(50)]
    public string SystemPayrollCode { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string PayrollCodeName { get; set; }

    [Column("Typical_Description")]
    [StringLength(100)]
    public string TypicalDescription { get; set; }

    [StringLength(50)]
    public string Comments { get; set; }

    public bool? Taxable { get; set; }

    public bool? Payment { get; set; }

    public bool? Deduction { get; set; }

    public bool? Posted { get; set; }

    [Column("Infiniti_Definition")]
    [StringLength(100)]
    public string InfinitiDefinition { get; set; }

    [Column("P9COLUMN")]
    public int? P9column { get; set; }
}