// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblTimeSheet")]
public partial class TblTimeSheet
{
    [Key]
    [Column("TIMESHEET_ID")]
    public int TimesheetId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("HOURS_WORKED")]
    public double? HoursWorked { get; set; }

    [Column("DAYS_WORKED")]
    public double? DaysWorked { get; set; }

    [Column("PUBLIC_HOLIDAY")]
    public bool PublicHoliday { get; set; }
}