// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblUser")]
public partial class TblUser
{
    [Column("USER_ID")]
    public int UserId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("USERNAME")]
    [StringLength(50)]
    public string Username { get; set; }

    [Column("PASSWORD")]
    [StringLength(250)]
    public string Password { get; set; }

    [Column("GROUPID")]
    [StringLength(50)]
    public string Groupid { get; set; }

    [Column("GROUPNAME")]
    [StringLength(50)]
    public string Groupname { get; set; }

    [Column("EMPCODE")]
    [StringLength(50)]
    public string Empcode { get; set; }

    [Column("EMPNAME")]
    [StringLength(50)]
    public string Empname { get; set; }

    [Column("DEPTCODE")]
    [StringLength(50)]
    public string Deptcode { get; set; }

    [Column("DEPTNAME")]
    [StringLength(50)]
    public string Deptname { get; set; }

    [Column("DATECREATED", TypeName = "smalldatetime")]
    public DateTime? Datecreated { get; set; }

    [Column("PASSWORD_CHANGED", TypeName = "smalldatetime")]
    public DateTime? PasswordChanged { get; set; }

    [Column("EXEMPT_RULE")]
    public bool ExemptRule { get; set; }

    [Column("DISABLE_ACCOUNT")]
    public bool DisableAccount { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("MACHINE")]
    [StringLength(50)]
    public string Machine { get; set; }

    [Column("LOGIN_ATTEMPTS")]
    public int? LoginAttempts { get; set; }

    [Column("LOCK_TIME", TypeName = "smalldatetime")]
    public DateTime? LockTime { get; set; }

    [Column("UNLOCK_TIME", TypeName = "smalldatetime")]
    public DateTime? UnlockTime { get; set; }

    [Column("LOGIN_TIME", TypeName = "smalldatetime")]
    public DateTime? LoginTime { get; set; }
}