// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblVarTr")]
public partial class TblVarTr
{
    [Column("Payslip_ID")]
    public long PayslipId { get; set; }

    [Column("Employee_Id")]
    public int? EmployeeId { get; set; }

    [Column("Payrollcode_Id")]
    public int? PayrollcodeId { get; set; }

    [Column("pDescription")]
    [StringLength(250)]
    public string PDescription { get; set; }

    public double? Amount { get; set; }

    [Column(TypeName = "money")]
    public decimal? PrevAmount { get; set; }
}