// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tempAdd")]
public partial class TempAdd
{
    [Column(TypeName = "smalldatetime")]
    public DateTime? Demp { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string EmpCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Surname { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OtherNames { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string BankName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BranchName { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string AccountNo { get; set; }

    [StringLength(200)]
    [Unicode(false)]
    public string NssfNo { get; set; }

    public int? EmpId { get; set; }
}