// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("u_rolerights")]
public partial class URoleright
{
    [Required]
    [Column("rolecode")]
    [StringLength(100)]
    [Unicode(false)]
    public string Rolecode { get; set; }

    [Column("table_code")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableCode { get; set; }

    [Column("allow_view")]
    public int? AllowView { get; set; }

    [Column("allow_delete")]
    public int? AllowDelete { get; set; }

    [Column("allow_insert")]
    public int? AllowInsert { get; set; }

    [Column("allow_update")]
    public int? AllowUpdate { get; set; }
}