// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("Visa")]
public partial class Visa
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(50)]
    public string Permit { get; set; }

    [StringLength(50)]
    public string Class { get; set; }

    public int? Years { get; set; }

    [Column("CFrom", TypeName = "smalldatetime")]
    public DateTime? Cfrom { get; set; }

    [Column("CTo", TypeName = "smalldatetime")]
    public DateTime? Cto { get; set; }

    [Column("KES")]
    [StringLength(50)]
    public string Kes { get; set; }

    [StringLength(50)]
    public string RcptNo { get; set; }

    [StringLength(100)]
    public string Nationality { get; set; }

    [StringLength(100)]
    public string Title { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}