// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

public partial class WfcBudgetPeriod
{
    [Key]
    public long BudgetperiodId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BudgetPerioddescription { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BudgetPeriodStartDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? BudgetPeriodEndDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BudgetPeriodStatus { get; set; }
}