// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("ACategory")]
public partial class Acategory
{
    [StringLength(20)]
    public string Period { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }
   [Key]
    [Column("ACode")]
    [StringLength(20)]
    public string Acode { get; set; }

    [Column("CCode")]
    [StringLength(20)]
    public string Ccode { get; set; }

    [StringLength(50)]
    public string Criteria { get; set; }

    [Column(TypeName = "money")]
    public decimal? Marks { get; set; }

    [Column("RCode")]
    [StringLength(20)]
    public string Rcode { get; set; }
}