// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("audittrail")]
public partial class Audittrail
{
    [Column("id")]
    public int Id { get; set; }

    public int? AuditCode { get; set; }
    [Key]
    [Column("UserID")]
    [StringLength(20)]
    public string UserId { get; set; }

    [Column("DTime")]
    [StringLength(50)]
    public string Dtime { get; set; }

    [StringLength(200)]
    public string Trans { get; set; }

    [Column("TDesc")]
    [StringLength(200)]
    public string Tdesc { get; set; }

    [StringLength(50)]
    public string MySection { get; set; }

    [Column("UID")]
    [StringLength(50)]
    public string Uid { get; set; }

    [Column("CFORM")]
    [StringLength(200)]
    public string Cform { get; set; }

    [Column("CACTION")]
    [StringLength(200)]
    public string Caction { get; set; }

    [Column("ADATETIME", TypeName = "smalldatetime")]
    public DateTime? Adatetime { get; set; }

    [Column("AVALUES", TypeName = "ntext")]
    public string Avalues { get; set; }

    [StringLength(50)]
    public string Subsystem { get; set; }
}