// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("bio")]
public partial class Bio
{
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string BioData { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
    [Key] 
    [Column("employee_id")]
    public long? EmployeeId { get; set; }
}