// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
public partial class Bonu
{
    public int? Code { get; set; }

    public int? Description { get; set; }
    [Key]
    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Perc { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}