// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
public partial class Contract
{
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("CFrom", TypeName = "smalldatetime")]
    public DateTime? Cfrom { get; set; }

    [Column("CTo", TypeName = "smalldatetime")]
    public DateTime? Cto { get; set; }

    [StringLength(200)]
    public string Ref { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
    [Key]
    [Column("employee_id")]
    public long? EmployeeId { get; set; }
}