// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("c_tables")]
public partial class CTable
{
    [Key]
    [Column("table_code")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableCode { get; set; }

    [Column("table_code_description")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableCodeDescription { get; set; }

    [Column("table_code_value")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableCodeValue { get; set; }

    [Column("table_type")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableType { get; set; }

    [Column("table_user_system_type")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableUserSystemType { get; set; }

    [Column("table_description")]
    [StringLength(100)]
    [Unicode(false)]
    public string TableDescription { get; set; }
}