// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("divapp")]
public partial class Divapp
{
    [Column("DCode")]
    [StringLength(20)]
    public string Dcode { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [Column("MApp")]
    [StringLength(5)]
    public string Mapp { get; set; }
    [Key]
    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}