// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("divisions")]
public partial class Division
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [Column("DCode")]
    [StringLength(20)]
    public string Dcode { get; set; }

    [StringLength(200)]
    public string Name { get; set; }

    [StringLength(50)]
    public string TelNo { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(50)]
    public string Fax { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [Column("MPerc")]
    public int? Mperc { get; set; }
}