// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("DOB&GenSearch")]
public partial class DobGenSearch
{
    [StringLength(20)]
    public string EmpCode { get; set; }
    [Key]
    [Column("DOB", TypeName = "smalldatetime")]
    public DateTime? Dob { get; set; }

    [StringLength(50)]
    public string Gender { get; set; }
}