// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("DOBOnlySearch")]
public partial class DobonlySearch
{
    [StringLength(20)]
    public string EmpCode { get; set; }
    [Key]
    [Column("DOB", TypeName = "smalldatetime")]
    public DateTime? Dob { get; set; }
}