// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("ECategory")]
public partial class Ecategory
{
    [Key]
    [Column("ECategory_id")]
    public int EcategoryId { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [StringLength(5)]
    public string Seq { get; set; }

    [Column(TypeName = "money")]
    public decimal? LowestSalary { get; set; }

    [Column(TypeName = "money")]
    public decimal? HighestSalary { get; set; }
}