// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("edu")]
public partial class Edu
{
    [Column("id")]
    public int Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Course { get; set; }

    [Column("CFrom")]
    [StringLength(10)]
    public string Cfrom { get; set; }

    [Column("CTo")]
    [StringLength(10)]
    public string Cto { get; set; }

    [Column("ELevel")]
    [StringLength(200)]
    public string Elevel { get; set; }

    [StringLength(200)]
    public string Award { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
    [Key]
    [Column("employee_id")]
    public int? EmployeeId { get; set; }

    [StringLength(100)]
    public string Institution { get; set; }
}