// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("employment")]
public partial class Employment
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Employer { get; set; }

    [Column("CFrom")]
    [StringLength(50)]
    public string Cfrom { get; set; }

    [Column("CTo")]
    [StringLength(50)]
    public string Cto { get; set; }

    [StringLength(200)]
    public string Reasons { get; set; }

    [Column("RName")]
    [StringLength(200)]
    public string Rname { get; set; }

    [StringLength(200)]
    public string Desig { get; set; }

    [StringLength(200)]
    public string Super { get; set; }

    [Column(TypeName = "money")]
    public decimal? Salary { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [StringLength(100)]
    public string Address { get; set; }

    [StringLength(50)]
    public string Phone { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}