// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    [Column("employee_id")]
    public long EmployeeId { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(100)]
    public string OtherNames { get; set; }

    [StringLength(100)]
    public string SurName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Title { get; set; }

    [Column("IDNo")]
    [StringLength(12)]
    public string Idno { get; set; }

    [Column("DOB", TypeName = "datetime")]
    public DateTime? Dob { get; set; }

    [StringLength(50)]
    public string Gender { get; set; }

    [Column("DEmployed", TypeName = "datetime")]
    public DateTime? Demployed { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Dleft { get; set; }

    [StringLength(200)]
    public string Desig { get; set; }

    [Column("DCode")]
    [StringLength(20)]
    public string Dcode { get; set; }

    [Column("HAddress")]
    [StringLength(200)]
    public string Haddress { get; set; }

    [Column("HTel")]
    [StringLength(50)]
    public string Htel { get; set; }

    [StringLength(50)]
    public string Email { get; set; }

    [Column("PEmployer")]
    [StringLength(100)]
    public string Pemployer { get; set; }

    [Column("NHIFNo")]
    [StringLength(12)]
    public string Nhifno { get; set; }

    [Column("NSSFNo")]
    [StringLength(50)]
    public string Nssfno { get; set; }

    [Column("LASCNo")]
    [StringLength(12)]
    public string Lascno { get; set; }

    [Column("PINNo")]
    [StringLength(12)]
    public string Pinno { get; set; }

    [Column("CCode")]
    [StringLength(20)]
    public string Ccode { get; set; }

    [StringLength(20)]
    public string CurCode { get; set; }

    [StringLength(12)]
    public string Type { get; set; }

    [StringLength(12)]
    public string Terms { get; set; }

    [Column("GCode")]
    [StringLength(20)]
    public string Gcode { get; set; }

    [StringLength(200)]
    public string MsgCode { get; set; }

    [Column(TypeName = "money")]
    public decimal? BasicPay { get; set; }

    [Column("OBasicPay", TypeName = "money")]
    public decimal? ObasicPay { get; set; }

    [Column("HTown")]
    [StringLength(50)]
    public string Htown { get; set; }

    [Column("DBirth")]
    [StringLength(50)]
    public string Dbirth { get; set; }

    [StringLength(50)]
    public string Location { get; set; }

    [StringLength(50)]
    public string SubLocation { get; set; }

    [StringLength(50)]
    public string Village { get; set; }

    [StringLength(50)]
    public string Religion { get; set; }

    public bool? Term { get; set; }

    [StringLength(50)]
    public string TermReasons { get; set; }

    [Column("ECategory_id")]
    public int? EcategoryId { get; set; }

    [Column("ECategory")]
    [StringLength(50)]
    public string Ecategory { get; set; }

    [Column("LAllow", TypeName = "money")]
    public decimal? Lallow { get; set; }

    [Column("OLAllow", TypeName = "money")]
    public decimal? Olallow { get; set; }

    [Column("HAllow", TypeName = "money")]
    public decimal? Hallow { get; set; }

    [Column("OHAllow", TypeName = "money")]
    public decimal? Ohallow { get; set; }

    [Column("OAllow", TypeName = "money")]
    public decimal? Oallow { get; set; }

    [Column("OOAllow", TypeName = "money")]
    public decimal? Ooallow { get; set; }

    [Column("TAllow", TypeName = "money")]
    public decimal? Tallow { get; set; }

    [Column("OTAllow", TypeName = "money")]
    public decimal? Otallow { get; set; }

    [StringLength(20)]
    public string TermTrain { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TermDate { get; set; }

    [StringLength(200)]
    public string Advisor { get; set; }

    [StringLength(20)]
    public string Achieved { get; set; }

    [StringLength(50)]
    public string CertNo { get; set; }

    [StringLength(50)]
    public string Nationality { get; set; }

    [StringLength(50)]
    public string Tribe { get; set; }

    public bool? Pension { get; set; }

    public bool? Disabled { get; set; }

    public bool? Payroll { get; set; }

    [Column("CV")]
    public bool? Cv { get; set; }

    public bool? AppForm { get; set; }

    public bool? Letters { get; set; }

    public bool? Medical { get; set; }

    public bool? Handbook { get; set; }

    public bool? Appointment { get; set; }

    [Column("IDCardCopy")]
    public bool? IdcardCopy { get; set; }

    [Column("NHIFCopy")]
    public bool? Nhifcopy { get; set; }

    [Column("NSSFCopy")]
    public bool? Nssfcopy { get; set; }

    [Column("PINCopy")]
    public bool? Pincopy { get; set; }

    public bool? JobDesc { get; set; }

    public bool? JobTraining { get; set; }

    [Column(TypeName = "money")]
    public decimal? Bonus { get; set; }

    [Column("BPerc", TypeName = "money")]
    public decimal? Bperc { get; set; }

    public bool? Orientation { get; set; }

    public bool? Unsolicited { get; set; }

    [Column("RChecks")]
    public bool? Rchecks { get; set; }

    public bool? Breakdown { get; set; }

    public bool? CashBonus { get; set; }

    [Column("RBonus", TypeName = "money")]
    public decimal? Rbonus { get; set; }

    [Column("CBonus", TypeName = "money")]
    public decimal? Cbonus { get; set; }

    public bool? RespBonus { get; set; }

    [Column(TypeName = "money")]
    public decimal? Prob { get; set; }

    [StringLength(200)]
    public string ProbationReason { get; set; }

    [Column("CDate", TypeName = "datetime")]
    public DateTime? Cdate { get; set; }

    [Column("SPension", TypeName = "datetime")]
    public DateTime? Spension { get; set; }

    [StringLength(50)]
    public string ProbType { get; set; }

    [Column("PSDate", TypeName = "datetime")]
    public DateTime? Psdate { get; set; }

    [StringLength(50)]
    public string BankCode { get; set; }

    [StringLength(50)]
    public string BankName { get; set; }

    [StringLength(50)]
    public string BankBranch { get; set; }

    [StringLength(50)]
    public string BankBranchName { get; set; }

    [StringLength(50)]
    public string AccountNo { get; set; }

    [Column("KRAFileNo")]
    [StringLength(50)]
    public string KrafileNo { get; set; }

    [Column("CStructure_id")]
    public int? CstructureId { get; set; }

    [Column("Payroll_id")]
    public int? PayrollId { get; set; }

    public bool? Unionisable { get; set; }

    [StringLength(50)]
    public string PayrollNo { get; set; }

    [Column("Marital_Status")]
    [StringLength(50)]
    public string MaritalStatus { get; set; }

    [Column("Postal_Code")]
    [StringLength(50)]
    public string PostalCode { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [Column("Cell_No")]
    [StringLength(50)]
    public string CellNo { get; set; }

    [StringLength(50)]
    public string Country { get; set; }

    [Column("Sacco_Number")]
    [StringLength(50)]
    public string SaccoNumber { get; set; }

    [Column("Pension_Number")]
    [StringLength(50)]
    public string PensionNumber { get; set; }

    [Column("Date_of_Expiry", TypeName = "datetime")]
    public DateTime? DateOfExpiry { get; set; }

    [Column("Paypoint_ID")]
    public int? PaypointId { get; set; }

    [StringLength(50)]
    public string Ethnic { get; set; }

    [StringLength(50)]
    public string Citizenship { get; set; }

    [StringLength(50)]
    public string BranchCode { get; set; }

    [Column("onleave")]
    public bool? Onleave { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateLeft { get; set; }

    [StringLength(50)]
    public string EmpGrades { get; set; }

    [Column("ECode")]
    [StringLength(10)]
    [Unicode(false)]
    public string Ecode { get; set; }

    [Column("TGrade")]
    [StringLength(10)]
    [Unicode(false)]
    public string Tgrade { get; set; }

    [Column("CCont")]
    [StringLength(10)]
    [Unicode(false)]
    public string Ccont { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string MyShift { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string MainAcctNo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string AcctBank { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EmploymentValidThro { get; set; }

    public bool? CanReEngage { get; set; }

    [StringLength(100)]
    public string PhysicalAddress { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Passport { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AlienNo { get; set; }

    [Column("age")]
    public int? Age { get; set; }

    [Column("SUSPENDED")]
    public bool? Suspended { get; set; }
}