// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

public partial class EmployeeBank
{
    [Key]
    [Column("EMPLOYEEBANKID")]
    public int Employeebankid { get; set; }

    [Column("Employee_ID")]
    public int? EmployeeId { get; set; }

    [Column("BranchID")]
    public int? BranchId { get; set; }

    [StringLength(50)]
    public string AccNumber { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string AccType { get; set; }

    public bool? MainAcct { get; set; }

    [StringLength(50)]
    public string EmpCode { get; set; }

    [StringLength(250)]
    public string EmpName { get; set; }

    [StringLength(100)]
    public string Bank { get; set; }

    [StringLength(250)]
    public string Branch { get; set; }

    public int? BankId { get; set; }
}