// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

public partial class EmpTerm
{
    [Key]
    public int TermsId { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [Column("UUser")]
    [StringLength(50)]
    public string Uuser { get; set; }

    [Column("TTime", TypeName = "smalldatetime")]
    public DateTime? Ttime { get; set; }
}