// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("GeneralOpt")]
public partial class GeneralOpt
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("PSave")]
    [StringLength(50)]
    public string Psave { get; set; }

    [Column("CName")]
    [StringLength(200)]
    public string Cname { get; set; }

    [StringLength(50)]
    public string Subsystem { get; set; }

    [Column("DGNo")]
    [StringLength(50)]
    public string Dgno { get; set; }

    [Column("DPass")]
    [StringLength(50)]
    public string Dpass { get; set; }

    [Column("IDiv")]
    [StringLength(5)]
    public string Idiv { get; set; }

    [Column("PRate")]
    public double? Prate { get; set; }

    [Column("CPass")]
    [StringLength(5)]
    public string Cpass { get; set; }

    [StringLength(5)]
    public string GenId { get; set; }

    [Column("IDInitials")]
    [StringLength(20)]
    public string Idinitials { get; set; }

    public int? StartFrom { get; set; }

    public int? LastSecId { get; set; }

    [Column("OmnisDB")]
    [StringLength(5)]
    public string OmnisDb { get; set; }

    [Column("DSource")]
    [StringLength(20)]
    public string Dsource { get; set; }

    [Column("DBase")]
    [StringLength(50)]
    public string Dbase { get; set; }

    [StringLength(20)]
    public string AppGroup { get; set; }

    [Column("UDays")]
    public double? Udays { get; set; }

    [Column("SRes")]
    [StringLength(5)]
    public string Sres { get; set; }

    [Column("myColor")]
    public int? MyColor { get; set; }

    [StringLength(5)]
    public string AuditTrail { get; set; }

    [StringLength(5)]
    public string Dis { get; set; }

    [StringLength(50)]
    public string DisBase { get; set; }

    [StringLength(5)]
    public string Recruit { get; set; }

    [StringLength(50)]
    public string RecBase { get; set; }

    [Column("ADBase")]
    [StringLength(5)]
    public string Adbase { get; set; }

    [Column("LPerc")]
    [StringLength(5)]
    public string Lperc { get; set; }

    public double? Perc { get; set; }

    [Column("MRet")]
    [StringLength(50)]
    public string Mret { get; set; }

    [Column("FRet")]
    [StringLength(50)]
    public string Fret { get; set; }

    [Column("RDays")]
    public int? Rdays { get; set; }

    [Column("BDays")]
    public int? Bdays { get; set; }

    [Column("VSal")]
    [StringLength(20)]
    public string Vsal { get; set; }

    public int? ContractsP { get; set; }

    public int? VisasP { get; set; }

    public int? CasualsP { get; set; }

    [Column("PDays")]
    public int? Pdays { get; set; }

    [Column("cyearend", TypeName = "datetime")]
    public DateTime? Cyearend { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string ServerName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string ConnectionName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string UserId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Passwd { get; set; }

    [Column("DCatalog")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dcatalog { get; set; }

    [Column("trainingreminderOption")]
    public bool? TrainingreminderOption { get; set; }

    [Column("trainingreminder", TypeName = "numeric(18, 0)")]
    public decimal? Trainingreminder { get; set; }

    [StringLength(50)]
    public string SatWorking { get; set; }

    [StringLength(50)]
    public string SunWorking { get; set; }

    [StringLength(50)]
    public string HolWorking { get; set; }

    public double? ExpiryPrompt { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? AppraisalDate { get; set; }
}