// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("GPosting")]
public partial class Gposting
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(100)]
    public string SurName { get; set; }

    [StringLength(100)]
    public string OtherNames { get; set; }

    public int? MySeq { get; set; }
    [Key]
    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}