// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("groups")]
public partial class Group
{
    [Key]
    [Column("GNo")]
    [StringLength(50)]
    public string Gno { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [StringLength(50)]
    public string Emp { get; set; }

    [StringLength(50)]
    public string Ben { get; set; }

    [StringLength(50)]
    public string Ded { get; set; }

    [StringLength(50)]
    public string Other { get; set; }

    [StringLength(50)]
    public string Setup { get; set; }

    [Column("UUser")]
    [StringLength(50)]
    public string Uuser { get; set; }

    [Column("TTime", TypeName = "smalldatetime")]
    public DateTime? Ttime { get; set; }

    [StringLength(50)]
    public string Subsystem { get; set; }
}