// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("JDescription")]
public partial class Jdescription
{
    [StringLength(250)]
    public string Description { get; set; }

    [StringLength(250)]
    public string Qualification { get; set; }
}