// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("JProg")]
public partial class Jprog
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Position { get; set; }

    [Column("CDate", TypeName = "datetime")]
    public DateTime? Cdate { get; set; }

    [Column(TypeName = "money")]
    public decimal? BasicPay { get; set; }

    [Column("HAllow", TypeName = "money")]
    public decimal? Hallow { get; set; }

    [Column("LAllow", TypeName = "money")]
    public decimal? Lallow { get; set; }

    [Column("TAllow", TypeName = "money")]
    public decimal? Tallow { get; set; }

    [Column("OAllow", TypeName = "money")]
    public decimal? Oallow { get; set; }

    [StringLength(50)]
    public string Category { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [Column("DCode")]
    [StringLength(20)]
    public string Dcode { get; set; }

    [StringLength(50)]
    public string MovementCode { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }

    [StringLength(50)]
    public string Terms { get; set; }
}