// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
public partial class Letter
{
    [Key]
    [Column("CCode")]
    [StringLength(20)]
    public string Ccode { get; set; }

    [Column("ACode")]
    [StringLength(20)]
    public string Acode { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("MCritaria")]
    [StringLength(20)]
    public string Mcritaria { get; set; }

    [StringLength(50)]
    public string Management { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [StringLength(200)]
    public string Groups { get; set; }

    [Column("PGroups")]
    [StringLength(5)]
    public string Pgroups { get; set; }
}