// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("LetterType")]
public partial class LetterType
{
    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(100)]
    public string Description { get; set; }

    [StringLength(5)]
    public string Admn { get; set; }

    [StringLength(5)]
    public string Seq { get; set; }

    public int? SeqNo { get; set; }

    [StringLength(5)]
    public string Expire { get; set; }
    [Key]
    [Column("EPeriod")]
    public int? Eperiod { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [Column("fromMark")]
    public int? FromMark { get; set; }

    public int? ToMark { get; set; }
}