// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;
[Keyless]
public partial class Module
{
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [StringLength(200)]
    public string Sec { get; set; }

    [StringLength(50)]
    public string SubSystem { get; set; }

    [StringLength(50)]
    public string Comments { get; set; }
}