// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("Nationality")]
public partial class Nationality
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}