// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
public partial class Need
{
    [Column("CCode")]
    [StringLength(20)]
    public string Ccode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [Column("PCode")]
    [StringLength(20)]
    public string Pcode { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("NBy")]
    [StringLength(200)]
    public string Nby { get; set; }

    [StringLength(50)]
    public string Internal { get; set; }

    [Column("AInternal")]
    [StringLength(50)]
    public string Ainternal { get; set; }

    [Column(TypeName = "money")]
    public decimal? Perc { get; set; }

    [Column("APerc", TypeName = "money")]
    public decimal? Aperc { get; set; }

    [StringLength(200)]
    public string Intend { get; set; }

    [Column("AIntend")]
    [StringLength(200)]
    public string Aintend { get; set; }

    [Column("AComments")]
    [StringLength(200)]
    public string Acomments { get; set; }

    [Column("ACharge")]
    [StringLength(50)]
    public string Acharge { get; set; }

    [StringLength(100)]
    public string Status { get; set; }

    public double? Positions { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }

    [Column("TFrom", TypeName = "smalldatetime")]
    public DateTime? Tfrom { get; set; }

    [Column("TTo", TypeName = "smalldatetime")]
    public DateTime? Tto { get; set; }

    [Column("TComments")]
    [StringLength(200)]
    public string Tcomments { get; set; }
}