// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("New_AuditTrail")]
public partial class NewAuditTrail
{
    [Column("UserID")]
    [StringLength(50)]
    [Unicode(false)]
    public string UserId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateOfAction { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? TimeOfAction { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Action { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Subsystem { get; set; }
}