// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("NewQualification")]
public partial class NewQualification
{
    [StringLength(250)]
    public string Description { get; set; }

    [StringLength(250)]
    public string Qualification { get; set; }
    [Key]
    [Column("myReq")]
    [StringLength(50)]
    public string MyReq { get; set; }
}