// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("NODateSearch")]
public partial class NodateSearch
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(50)]
    public string Gender { get; set; }

    [Column("myQualification")]
    [StringLength(200)]
    public string MyQualification { get; set; }

    [StringLength(50)]
    public string Marks { get; set; }
}