// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

public partial class OntimePayrollContext : DbContext
{
    public OntimePayrollContext(DbContextOptions<OntimePayrollContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Acategory> Acategories { get; set; }

    public virtual DbSet<Acomment> Acomments { get; set; }

    public virtual DbSet<Aentry> Aentries { get; set; }

    public virtual DbSet<Aletter> Aletters { get; set; }

    public virtual DbSet<AllSearch> AllSearches { get; set; }

    public virtual DbSet<Aperiod> Aperiods { get; set; }

    public virtual DbSet<Atype> Atypes { get; set; }

    public virtual DbSet<Audittrail> Audittrails { get; set; }

    public virtual DbSet<Award> Awards { get; set; }

    public virtual DbSet<BankDetail> BankDetails { get; set; }

    public virtual DbSet<Bio> Bios { get; set; }

    public virtual DbSet<Bonu> Bonus { get; set; }

    public virtual DbSet<Btype> Btypes { get; set; }

    public virtual DbSet<CTable> CTables { get; set; }

    public virtual DbSet<CTableDetail> CTableDetails { get; set; }

    public virtual DbSet<Casual> Casuals { get; set; }

    public virtual DbSet<CompanyAsset> CompanyAssets { get; set; }

    public virtual DbSet<CompanyAssetIssue> CompanyAssetIssues { get; set; }

    public virtual DbSet<CompanyLogo> CompanyLogos { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<Contract> Contracts { get; set; }

    public virtual DbSet<Cstructure> Cstructures { get; set; }

    public virtual DbSet<Ctype> Ctypes { get; set; }

    public virtual DbSet<Cuser> Cusers { get; set; }

    public virtual DbSet<DCaseRating> DCaseRatings { get; set; }

    public virtual DbSet<Divapp> Divapps { get; set; }

    public virtual DbSet<Division> Divisions { get; set; }

    public virtual DbSet<DobGenSearch> DobGenSearches { get; set; }

    public virtual DbSet<DobQualSearch> DobQualSearches { get; set; }

    public virtual DbSet<DobonlySearch> DobonlySearches { get; set; }

    public virtual DbSet<Ecategory> Ecategories { get; set; }

    public virtual DbSet<EditLetter> EditLetters { get; set; }

    public virtual DbSet<Edu> Edus { get; set; }

    public virtual DbSet<Education> Educations { get; set; }

    public virtual DbSet<EmpDet> EmpDets { get; set; }

    public virtual DbSet<EmpTerm> EmpTerms { get; set; }

    public virtual DbSet<Empacct> Empaccts { get; set; }

    public virtual DbSet<Empdivision> Empdivisions { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<EmployeeBank> EmployeeBanks { get; set; }

    public virtual DbSet<EmployeeHistory> EmployeeHistories { get; set; }

    public virtual DbSet<Employment> Employments { get; set; }

    public virtual DbSet<Experience> Experiences { get; set; }

    public virtual DbSet<Family> Families { get; set; }

    public virtual DbSet<GenOnlySearch> GenOnlySearches { get; set; }

    public virtual DbSet<GeneralOpt> GeneralOpts { get; set; }

    public virtual DbSet<Gposting> Gpostings { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<GroupCat> GroupCats { get; set; }

    public virtual DbSet<GroupModule> GroupModules { get; set; }

    public virtual DbSet<Jdescription> Jdescriptions { get; set; }

    public virtual DbSet<Jprog> Jprogs { get; set; }

    public virtual DbSet<Kin> Kins { get; set; }

    public virtual DbSet<Lcategory> Lcategories { get; set; }

    public virtual DbSet<Lentry> Lentries { get; set; }

    public virtual DbSet<Letter> Letters { get; set; }

    public virtual DbSet<LetterType> LetterTypes { get; set; }

    public virtual DbSet<LevelType> LevelTypes { get; set; }

    public virtual DbSet<Lgroup> Lgroups { get; set; }

    public virtual DbSet<Lperiod> Lperiods { get; set; }

    public virtual DbSet<Lscategory> Lscategories { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<Name> Names { get; set; }

    public virtual DbSet<Nationality> Nationalities { get; set; }

    public virtual DbSet<Need> Needs { get; set; }

    public virtual DbSet<NewAuditTrail> NewAuditTrails { get; set; }

    public virtual DbSet<NewNeed> NewNeeds { get; set; }

    public virtual DbSet<NewQualification> NewQualifications { get; set; }

    public virtual DbSet<NoGenderSearch> NoGenderSearches { get; set; }

    public virtual DbSet<NoMarkSearch> NoMarkSearches { get; set; }

    public virtual DbSet<NoQualifSearch> NoQualifSearches { get; set; }

    public virtual DbSet<NodateSearch> NodateSearches { get; set; }

    public virtual DbSet<Nprocess> Nprocesses { get; set; }

    public virtual DbSet<OriginalSal> OriginalSals { get; set; }

    public virtual DbSet<Papproval> Papprovals { get; set; }

    public virtual DbSet<PayrollForm> PayrollForms { get; set; }

    public virtual DbSet<PdCbscat> PdCbscats { get; set; }

    public virtual DbSet<PdCompanyCodesCat> PdCompanyCodesCats { get; set; }

    public virtual DbSet<PdContractType> PdContractTypes { get; set; }

    public virtual DbSet<PdSalaryChange> PdSalaryChanges { get; set; }

    public virtual DbSet<Pdetail> Pdetails { get; set; }

    public virtual DbSet<Pgroup> Pgroups { get; set; }

    public virtual DbSet<PlevelDescr> PlevelDescrs { get; set; }

    public virtual DbSet<Position> Positions { get; set; }

    public virtual DbSet<PositionRequirement> PositionRequirements { get; set; }

    public virtual DbSet<PositionRequirementsValue> PositionRequirementsValues { get; set; }

    public virtual DbSet<PostCategory> PostCategories { get; set; }

    public virtual DbSet<PostCategory1> PostCategories1 { get; set; }

    public virtual DbSet<Prof> Profs { get; set; }

    public virtual DbSet<QualifOnlySearch> QualifOnlySearches { get; set; }

    public virtual DbSet<Qualification> Qualifications { get; set; }

    public virtual DbSet<ReInterview> ReInterviews { get; set; }

    public virtual DbSet<Ref> Refs { get; set; }

    public virtual DbSet<RefSource> RefSources { get; set; }

    public virtual DbSet<Religion> Religions { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<SalaryIncrease> SalaryIncreases { get; set; }

    public virtual DbSet<Scategory> Scategories { get; set; }

    public virtual DbSet<Security> Securities { get; set; }

    public virtual DbSet<Semp> Semps { get; set; }

    public virtual DbSet<Sletter> Sletters { get; set; }

    public virtual DbSet<Sreport> Sreports { get; set; }

    public virtual DbSet<Stype> Stypes { get; set; }

    public virtual DbSet<TblAccountLayout> TblAccountLayouts { get; set; }

    public virtual DbSet<TblAllTask> TblAllTasks { get; set; }

    public virtual DbSet<TblAllowance> TblAllowances { get; set; }

    public virtual DbSet<TblAssignedRight> TblAssignedRights { get; set; }

    public virtual DbSet<TblBank> TblBanks { get; set; }

    public virtual DbSet<TblBankBranch> TblBankBranches { get; set; }

    public virtual DbSet<TblBankBranch1> TblBankBranches1 { get; set; }

    public virtual DbSet<TblBankTransfer> TblBankTransfers { get; set; }

    public virtual DbSet<TblBonu> TblBonus { get; set; }

    public virtual DbSet<TblBonusDetail> TblBonusDetails { get; set; }

    public virtual DbSet<TblCasualEmployeeTransaction> TblCasualEmployeeTransactions { get; set; }

    public virtual DbSet<TblCasualPaymentCriterion> TblCasualPaymentCriteria { get; set; }

    public virtual DbSet<TblCasualPaymentPeriod> TblCasualPaymentPeriods { get; set; }

    public virtual DbSet<TblCitiBankTransfer> TblCitiBankTransfers { get; set; }

    public virtual DbSet<TblCompany> TblCompanies { get; set; }

    public virtual DbSet<TblCompanyBank> TblCompanyBanks { get; set; }

    public virtual DbSet<TblCompanyPaymentSummary> TblCompanyPaymentSummaries { get; set; }

    public virtual DbSet<TblContractType> TblContractTypes { get; set; }

    public virtual DbSet<TblControl> TblControls { get; set; }

    public virtual DbSet<TblCooperative> TblCooperatives { get; set; }

    public virtual DbSet<TblCostCenter> TblCostCenters { get; set; }

    public virtual DbSet<TblCostcenterRemuneration> TblCostcenterRemunerations { get; set; }

    public virtual DbSet<TblCurId> TblCurIds { get; set; }

    public virtual DbSet<TblCurrency> TblCurrencies { get; set; }

    public virtual DbSet<TblDailyTransaction> TblDailyTransactions { get; set; }

    public virtual DbSet<TblDefineCintributionBenefit> TblDefineCintributionBenefits { get; set; }

    public virtual DbSet<TblDefineContributionBenefit> TblDefineContributionBenefits { get; set; }

    public virtual DbSet<TblDefinedBenefit> TblDefinedBenefits { get; set; }

    public virtual DbSet<TblDenomination> TblDenominations { get; set; }

    public virtual DbSet<TblEmployee> TblEmployees { get; set; }

    public virtual DbSet<TblEmployeeAllowance> TblEmployeeAllowances { get; set; }

    public virtual DbSet<TblEmployeeBankNetPay> TblEmployeeBankNetPays { get; set; }

    public virtual DbSet<TblEmployeeBasicPayArrear> TblEmployeeBasicPayArrears { get; set; }

    public virtual DbSet<TblEmployeeBasicSalary> TblEmployeeBasicSalaries { get; set; }

    public virtual DbSet<TblEmployeeBenefit> TblEmployeeBenefits { get; set; }

    public virtual DbSet<TblEmployeeBonu> TblEmployeeBonus { get; set; }

    public virtual DbSet<TblEmployeeCasualPaymentCriterion> TblEmployeeCasualPaymentCriteria { get; set; }

    public virtual DbSet<TblEmployeeCooperative> TblEmployeeCooperatives { get; set; }

    public virtual DbSet<TblEmployeeCostCenter> TblEmployeeCostCenters { get; set; }

    public virtual DbSet<TblEmployeeDailyValue> TblEmployeeDailyValues { get; set; }

    public virtual DbSet<TblEmployeeDefinedBenefit> TblEmployeeDefinedBenefits { get; set; }

    public virtual DbSet<TblEmployeeHousing> TblEmployeeHousings { get; set; }

    public virtual DbSet<TblEmployeeInsurance> TblEmployeeInsurances { get; set; }

    public virtual DbSet<TblEmployeeLoan> TblEmployeeLoans { get; set; }

    public virtual DbSet<TblEmployeeMessage> TblEmployeeMessages { get; set; }

    public virtual DbSet<TblEmployeeMotorcar> TblEmployeeMotorcars { get; set; }

    public virtual DbSet<TblEmployeePayrollCode> TblEmployeePayrollCodes { get; set; }

    public virtual DbSet<TblEmployeePayrollPeriod> TblEmployeePayrollPeriods { get; set; }

    public virtual DbSet<TblEmployeePension> TblEmployeePensions { get; set; }

    public virtual DbSet<TblEmployeePeriodDetail> TblEmployeePeriodDetails { get; set; }

    public virtual DbSet<TblEmployeeRemuneration> TblEmployeeRemunerations { get; set; }

    public virtual DbSet<TblEmployeeTransaction> TblEmployeeTransactions { get; set; }

    public virtual DbSet<TblEmployeeType> TblEmployeeTypes { get; set; }

    public virtual DbSet<TblFormatCostCenter> TblFormatCostCenters { get; set; }

    public virtual DbSet<TblFringeBenefitTax> TblFringeBenefitTaxes { get; set; }

    public virtual DbSet<TblGroupControl> TblGroupControls { get; set; }

    public virtual DbSet<TblGroupModule> TblGroupModules { get; set; }

    public virtual DbSet<TblHeadOfDepartment> TblHeadOfDepartments { get; set; }

    public virtual DbSet<TblHeadOfSubDepartment> TblHeadOfSubDepartments { get; set; }

    public virtual DbSet<TblHoliday> TblHolidays { get; set; }

    public virtual DbSet<TblHomeOwnershipSavingsPlan> TblHomeOwnershipSavingsPlans { get; set; }

    public virtual DbSet<TblHousing> TblHousings { get; set; }

    public virtual DbSet<TblHousingScheme> TblHousingSchemes { get; set; }

    public virtual DbSet<TblInsuranceCompany> TblInsuranceCompanies { get; set; }

    public virtual DbSet<TblJv> TblJvs { get; set; }

    public virtual DbSet<TblJvreport> TblJvreports { get; set; }

    public virtual DbSet<TblLoanAdjustment> TblLoanAdjustments { get; set; }

    public virtual DbSet<TblLoanReduction> TblLoanReductions { get; set; }

    public virtual DbSet<TblLoanSchedule> TblLoanSchedules { get; set; }

    public virtual DbSet<TblLoanTopup> TblLoanTopups { get; set; }

    public virtual DbSet<TblLoanTransaction> TblLoanTransactions { get; set; }

    public virtual DbSet<TblMailSetUp> TblMailSetUps { get; set; }

    public virtual DbSet<TblModule> TblModules { get; set; }

    public virtual DbSet<TblModule1> TblModules1 { get; set; }

    public virtual DbSet<TblMotorCar> TblMotorCars { get; set; }

    public virtual DbSet<TblNhif> TblNhifs { get; set; }

    public virtual DbSet<TblNonPayrollTransaction> TblNonPayrollTransactions { get; set; }

    public virtual DbSet<TblNssf> TblNssfs { get; set; }

    public virtual DbSet<TblNssfSfi> TblNssfSfis { get; set; }

    public virtual DbSet<TblOpeningBalance> TblOpeningBalances { get; set; }

    public virtual DbSet<TblOption> TblOptions { get; set; }

    public virtual DbSet<TblOtherOption> TblOtherOptions { get; set; }

    public virtual DbSet<TblOverDrawn> TblOverDrawns { get; set; }

    public virtual DbSet<TblOverWrite> TblOverWrites { get; set; }

    public virtual DbSet<TblOwnerOccupiedInterest> TblOwnerOccupiedInterests { get; set; }

    public virtual DbSet<TblPasswordRule> TblPasswordRules { get; set; }

    public virtual DbSet<TblPayRollGrade> TblPayRollGrades { get; set; }

    public virtual DbSet<TblPaye> TblPayes { get; set; }

    public virtual DbSet<TblPayeTanzanium> TblPayeTanzania { get; set; }

    public virtual DbSet<TblPayeUgandum> TblPayeUganda { get; set; }

    public virtual DbSet<TblPayeYearly> TblPayeYearlies { get; set; }

    public virtual DbSet<TblPaypoint> TblPaypoints { get; set; }

    public virtual DbSet<TblPayroll> TblPayrolls { get; set; }

    public virtual DbSet<TblPayrollCode> TblPayrollCodes { get; set; }

    public virtual DbSet<TblPayrollCodeRange> TblPayrollCodeRanges { get; set; }

    public virtual DbSet<TblPayrollTransaction> TblPayrollTransactions { get; set; }

    public virtual DbSet<TblPayslip> TblPayslips { get; set; }

    public virtual DbSet<TblPension> TblPensions { get; set; }

    public virtual DbSet<TblPeriod> TblPeriods { get; set; }

    public virtual DbSet<TblPeriodCompanyExpense> TblPeriodCompanyExpenses { get; set; }

    public virtual DbSet<TblPeriodDetail> TblPeriodDetails { get; set; }

    public virtual DbSet<TblPeriodTransaction> TblPeriodTransactions { get; set; }

    public virtual DbSet<TblPolicy> TblPolicies { get; set; }

    public virtual DbSet<TblPostingFormat> TblPostingFormats { get; set; }

    public virtual DbSet<TblPreviousPayeTable> TblPreviousPayeTables { get; set; }

    public virtual DbSet<TblProtime> TblProtimes { get; set; }

    public virtual DbSet<TblRangeBenefit> TblRangeBenefits { get; set; }

    public virtual DbSet<TblRelief> TblReliefs { get; set; }

    public virtual DbSet<TblRemuneration> TblRemunerations { get; set; }

    public virtual DbSet<TblSendPayslip> TblSendPayslips { get; set; }

    public virtual DbSet<TblServant> TblServants { get; set; }

    public virtual DbSet<TblService> TblServices { get; set; }

    public virtual DbSet<TblServiceCharge> TblServiceCharges { get; set; }

    public virtual DbSet<TblServiceChargeDeduction> TblServiceChargeDeductions { get; set; }

    public virtual DbSet<TblServiceEmployee> TblServiceEmployees { get; set; }

    public virtual DbSet<TblSetting> TblSettings { get; set; }

    public virtual DbSet<TblStatementCode> TblStatementCodes { get; set; }

    public virtual DbSet<TblSystem> TblSystems { get; set; }

    public virtual DbSet<TblSystemError> TblSystemErrors { get; set; }

    public virtual DbSet<TblSystemPayrollCode> TblSystemPayrollCodes { get; set; }

    public virtual DbSet<TblTimeSheet> TblTimeSheets { get; set; }

    public virtual DbSet<TblTransaction> TblTransactions { get; set; }

    public virtual DbSet<TblTransactionType> TblTransactionTypes { get; set; }

    public virtual DbSet<TblUnusedRelief> TblUnusedReliefs { get; set; }

    public virtual DbSet<TblUser> TblUsers { get; set; }

    public virtual DbSet<TblUser1> TblUser1s { get; set; }

    public virtual DbSet<TblUserGroup> TblUserGroups { get; set; }

    public virtual DbSet<TblUserGroup1> TblUserGroup1s { get; set; }

    public virtual DbSet<TblUserGroup2> TblUserGroup2s { get; set; }

    public virtual DbSet<TblUserLog> TblUserLogs { get; set; }

    public virtual DbSet<TblVarTr> TblVarTrs { get; set; }

    public virtual DbSet<TblVariance> TblVariances { get; set; }

    public virtual DbSet<TempAdd> TempAdds { get; set; }

    public virtual DbSet<Tribe> Tribes { get; set; }

    public virtual DbSet<UAudittrail> UAudittrails { get; set; }

    public virtual DbSet<ULogin> ULogins { get; set; }

    public virtual DbSet<UPayrollAccess> UPayrollAccesses { get; set; }

    public virtual DbSet<UPolicysetting> UPolicysettings { get; set; }

    public virtual DbSet<URole> URoles { get; set; }

    public virtual DbSet<URoleright> URolerights { get; set; }

    public virtual DbSet<UUser> UUsers { get; set; }

    public virtual DbSet<UUser1> UUsers1 { get; set; }

    public virtual DbSet<UUserpwdhist> UUserpwdhists { get; set; }

    public virtual DbSet<Visa> Visas { get; set; }

    public virtual DbSet<WfcBudgetPeriod> WfcBudgetPeriods { get; set; }

    public virtual DbSet<YrsGroup> YrsGroups { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CTableDetail>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Cstructure>(entity =>
        {
            entity.Property(e => e.Loaded)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_cstructure_Loaded");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.EmployeeId).HasName("PK_Employee_1");

            entity.Property(e => e.AcctBank).IsFixedLength();
            entity.Property(e => e.Ccont).IsFixedLength();
            entity.Property(e => e.Ecode).IsFixedLength();
            entity.Property(e => e.MainAcctNo).IsFixedLength();
            entity.Property(e => e.MyShift).IsFixedLength();
            entity.Property(e => e.Suspended)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Employee_SUSPENDED");
            entity.Property(e => e.Tgrade).IsFixedLength();
            entity.Property(e => e.Title).IsFixedLength();
        });

        modelBuilder.Entity<EmployeeBank>(entity =>
        {
            entity.Property(e => e.MainAcct)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_EmployeeBanks_MainAcct");
        });

        modelBuilder.Entity<EmployeeHistory>(entity =>
        {
            entity.Property(e => e.Title).IsFixedLength();
        });

        modelBuilder.Entity<GeneralOpt>(entity =>
        {
            entity.Property(e => e.ConnectionName).IsFixedLength();
            entity.Property(e => e.Dcatalog).IsFixedLength();
            entity.Property(e => e.Passwd).IsFixedLength();
            entity.Property(e => e.ServerName).IsFixedLength();
            entity.Property(e => e.UserId).IsFixedLength();
        });

        modelBuilder.Entity<PayrollForm>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<Position>(entity =>
        {
            entity.Property(e => e.Approved)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Positions_Approved");
            entity.Property(e => e.Code).IsFixedLength();
        });

        modelBuilder.Entity<SalaryIncrease>(entity =>
        {
            entity.Property(e => e.Period).IsFixedLength();
        });

        modelBuilder.Entity<Security>(entity =>
        {
            entity.Property(e => e.CategoryAccess).IsFixedLength();
        });

        modelBuilder.Entity<Semp>(entity =>
        {
            entity.ToTable("semp", tb => tb.HasTrigger("updateCStructureID"));

            entity.Property(e => e.Hod)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_semp_HOD");
        });

        modelBuilder.Entity<Stype>(entity =>
        {
            entity.Property(e => e.Smain)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_stypes_SMain");
        });

        modelBuilder.Entity<TblCompanyBank>(entity =>
        {
            entity.Property(e => e.DefaultBank).HasAnnotation("Relational:DefaultConstraintName", "DF_tblCompanyBank_DEFAULT_BANK");
        });

        modelBuilder.Entity<TblCompanyPaymentSummary>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblDailyTransaction>(entity =>
        {
            entity.HasKey(e => e.DailyTransactionId).HasName("pk_DailyTrans");
        });

        modelBuilder.Entity<TblDefinedBenefit>(entity =>
        {
            entity.Property(e => e.Isamount)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblDefinedBenefits_ISAMOUNT");
        });

        modelBuilder.Entity<TblEmployee>(entity =>
        {
            entity.Property(e => e.EmployeeId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblEmployeeBankNetPay>(entity =>
        {
            entity.Property(e => e.CompanybankId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBankNetPay_COMPANYBANK_ID");
            entity.Property(e => e.Reimbursement)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBankNetPay_Reimbursement");
        });

        modelBuilder.Entity<TblEmployeeBasicSalary>(entity =>
        {
            entity.Property(e => e.BankTransfer)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_BANK_TRANSFER");
            entity.Property(e => e.Cash)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_CASH");
            entity.Property(e => e.Cheque)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_CHEQUE");
            entity.Property(e => e.CurrentPay)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_CURRENT_PAY");
            entity.Property(e => e.Daily)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_DAILY");
            entity.Property(e => e.Hourly)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_HOURLY");
            entity.Property(e => e.Nhif)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_NHIF");
            entity.Property(e => e.Nssf)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_NSSF");
            entity.Property(e => e.Overwritenhif)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_OVERWRITENHIF");
            entity.Property(e => e.Overwritenssf)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_OVERWRITENSSF");
            entity.Property(e => e.Overwritepaye)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_OVERWRITEPAYE");
            entity.Property(e => e.Paye)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_PAYE");
            entity.Property(e => e.Weekly)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeBasicSalary_WEEKLY");
        });

        modelBuilder.Entity<TblEmployeeCostCenter>(entity =>
        {
            entity.Property(e => e.EmployeecostcenterId).ValueGeneratedOnAdd();
            entity.Property(e => e.Percentage)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeCostCenter_PRECENTAGE");
        });

        modelBuilder.Entity<TblEmployeeDailyValue>(entity =>
        {
            entity.HasKey(e => e.EmployeeDailyValueId).HasName("pk_EDVID");
        });

        modelBuilder.Entity<TblEmployeeDefinedBenefit>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblEmployeeInsurance>(entity =>
        {
            entity.Property(e => e.PolicyNo)
                .HasDefaultValueSql("(0)")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeInsurance_POLICY_NO");
        });

        modelBuilder.Entity<TblEmployeePayrollCode>(entity =>
        {
            entity.Property(e => e.FormatId).HasDefaultValue(0);
            entity.Property(e => e.IsRangeBenefit).HasDefaultValue(false);
        });

        modelBuilder.Entity<TblEmployeePayrollPeriod>(entity =>
        {
            entity.Property(e => e.EmployeeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePayrollPeriods_Employee_ID");
            entity.Property(e => e.PeriodYear).HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePayrollPeriods_Period_Year");
        });

        modelBuilder.Entity<TblEmployeePension>(entity =>
        {
            entity.Property(e => e.Active)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePension_ACTIVE");
            entity.Property(e => e.BalanceCwd)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePension_BALANCE_CWD");
            entity.Property(e => e.EmployerbalanceCwd)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePension_EMPLOYERBALANCE_CWD");
            entity.Property(e => e.Employermanualdeduction)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePension_EMPLOYERMANUALDEDUCTION");
            entity.Property(e => e.EmppensionId).ValueGeneratedOnAdd();
            entity.Property(e => e.Manualdeduction)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePension_MANUALDEDUCTION");
            entity.Property(e => e.PensionNo)
                .HasDefaultValue("-")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePension_PENSION_NO");
        });

        modelBuilder.Entity<TblEmployeePeriodDetail>(entity =>
        {
            entity.HasKey(e => e.EmployeepayId).HasName("PK_tblEmployeePeriodDetails_1");

            entity.Property(e => e.Allowances)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_ALLOWANCES");
            entity.Property(e => e.BasicPay)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_BASIC_PAY");
            entity.Property(e => e.Benefits)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_BENEFITS");
            entity.Property(e => e.CstructureId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_CSTRUCTURE_ID");
            entity.Property(e => e.DesignationId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_DESIGNATION_ID");
            entity.Property(e => e.EmployeeId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_EMPLOYEE_ID");
            entity.Property(e => e.GradeId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_GRADE_ID");
            entity.Property(e => e.GrossPay)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_GROSS_PAY");
            entity.Property(e => e.HouseAllowance)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_HOUSE_ALLOWANCE");
            entity.Property(e => e.InsuranceRelief)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_INSURANCE_RELIEF");
            entity.Property(e => e.NetPay)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_NET_PAY");
            entity.Property(e => e.Nhif)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_NHIF");
            entity.Property(e => e.Nssf)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_NSSF");
            entity.Property(e => e.Oointerest)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_OOINTEREST");
            entity.Property(e => e.Paye)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_PAYE");
            entity.Property(e => e.PeriodMonth)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_PERIOD_MONTH");
            entity.Property(e => e.PeriodYear)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_PERIOD_YEAR");
            entity.Property(e => e.Relief)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_RELIEF");
            entity.Property(e => e.TaxCharged)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_TAX_CHARGED");
            entity.Property(e => e.TaxablePay)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_TAXABLE_PAY");
            entity.Property(e => e.Valueofquarters)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeePeriodDetails_VALUEOFQUARTERS");
        });

        modelBuilder.Entity<TblEmployeeRemuneration>(entity =>
        {
            entity.Property(e => e.AmountValue)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeRemuneration_AMOUNT_VALUE");
            entity.Property(e => e.Isamount)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblEmployeeRemuneration_ISAMOUNT");
        });

        modelBuilder.Entity<TblEmployeeTransaction>(entity =>
        {
            entity.Property(e => e.FormatId).HasDefaultValue(0);
            entity.Property(e => e.IsRangeBenefit).HasDefaultValue(false);
        });

        modelBuilder.Entity<TblLoanAdjustment>(entity =>
        {
            entity.Property(e => e.LoanAdjustmentId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblLoanSchedule>(entity =>
        {
            entity.Property(e => e.EmployeeloanId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblLoanSchedule_EMPLOYEELOAN_ID");
            entity.Property(e => e.Interest)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblLoanSchedule_INTEREST");
            entity.Property(e => e.LoanAmount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblLoanSchedule_LOAN_AMOUNT");
            entity.Property(e => e.PeriodMonth)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblLoanSchedule_PERIOD_MONTH");
            entity.Property(e => e.PeriodYear)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblLoanSchedule_PERIOD_YEAR");
            entity.Property(e => e.RecoveryAmount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblLoanSchedule_RECOVERY_AMOUNT");
        });

        modelBuilder.Entity<TblMailSetUp>(entity =>
        {
            entity.Property(e => e.MailsetUpId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblNonPayrollTransaction>(entity =>
        {
            entity.Property(e => e.Amount).HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_Amount");
            entity.Property(e => e.Description)
                .HasDefaultValue("-")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_Description");
            entity.Property(e => e.EmployeeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_EmployeeId");
            entity.Property(e => e.PayrollCodeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_PayrollCodeId");
            entity.Property(e => e.PeriodMonth).HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_PeriodMonth");
            entity.Property(e => e.PeriodYear).HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_PeriodYear");
            entity.Property(e => e.ReceiptNo)
                .HasDefaultValue("-")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_ReceiptNo");
            entity.Property(e => e.TransDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_TransDate");
            entity.Property(e => e.TransType)
                .HasDefaultValue("P")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_TransType");
            entity.Property(e => e.UserId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblNonPayrollTransactions_UserId");
        });

        modelBuilder.Entity<TblOpeningBalance>(entity =>
        {
            entity.Property(e => e.EmployeeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblOPeningBalances_EMPLOYEE_ID");
            entity.Property(e => e.OpeningBalance).HasAnnotation("Relational:DefaultConstraintName", "DF_tblOPeningBalances_OPENING_BALANCE");
            entity.Property(e => e.PayrollcodeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblOPeningBalances_PAYROLLCODE_ID");
            entity.Property(e => e.PeriodMonth).HasAnnotation("Relational:DefaultConstraintName", "DF_tblOPeningBalances_PERIOD_MONTH");
            entity.Property(e => e.PeriodYear).HasAnnotation("Relational:DefaultConstraintName", "DF_tblOPeningBalances_PERIOD_YEAR");
        });

        modelBuilder.Entity<TblOption>(entity =>
        {
            entity.Property(e => e.EditLeave)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOptions_Edit_Leave");
            entity.Property(e => e.Ignorevalueofquarters)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOptions_IGNOREVALUEOFQUARTERS");
            entity.Property(e => e.LoanbenefitId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOptions_LOANBENEFIT_ID");
            entity.Property(e => e.NetpayRoundingCriteria).IsFixedLength();
            entity.Property(e => e.PayeRoundingCriteria).IsFixedLength();
            entity.Property(e => e.Rejectsaldeductions)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOptions_REJECTSALDEDUCTIONS");
        });

        modelBuilder.Entity<TblOtherOption>(entity =>
        {
            entity.Property(e => e.BlockPostingForLeave)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOtherOptions_BlockPostingForLeave");
            entity.Property(e => e.Nhifoption)
                .HasDefaultValue("grosspay")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOtherOptions_NHIFOption");
            entity.Property(e => e.ShowPrinterSetup)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOtherOptions_ShowPrinterSetup");
        });

        modelBuilder.Entity<TblOverWrite>(entity =>
        {
            entity.Property(e => e.EmployeeId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOverWrite_EMPLOYEE_ID");
            entity.Property(e => e.NhifOverwrite)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOverWrite_NHIF_OVERWRITE");
            entity.Property(e => e.NssfOverwrite)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOverWrite_NSSF_OVERWRITE");
            entity.Property(e => e.PayeOverwrite)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOverWrite_PAYE_OVERWRITE");
            entity.Property(e => e.PeriodMonth)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOverWrite_PERIOD_MONTH");
            entity.Property(e => e.PeriodYear)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblOverWrite_PERIOD_YEAR");
        });

        modelBuilder.Entity<TblPayeTanzanium>(entity =>
        {
            entity.Property(e => e.PayeId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblPayroll>(entity =>
        {
            entity.Property(e => e.PostDailyValues).HasDefaultValue(false);
        });

        modelBuilder.Entity<TblPayrollCode>(entity =>
        {
            entity.Property(e => e.ChargeEmployer).HasDefaultValue(false);
            entity.Property(e => e.CompanyId)
                .HasDefaultValue(1.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCode_COMPANY_ID");
            entity.Property(e => e.EmployerPerc).HasDefaultValue(0m);
            entity.Property(e => e.Exemptnssf).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCode_EXEMPTNSSF");
            entity.Property(e => e.FringeBenefit).IsFixedLength();
            entity.Property(e => e.IsCummulative).HasDefaultValue(false);
            entity.Property(e => e.Ispension)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCode_ISPENSION");
            entity.Property(e => e.Nssfinclusive).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCode_NSFFINCLUSIVE");
            entity.Property(e => e.Pensionemployeeperc).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCode_PENSIONEMPLOYEEPERC");
            entity.Property(e => e.Pensionemployerperc).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCode_PENSIONEMPLOYERPERC");
            entity.Property(e => e.Separated)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_Separated");
            entity.Property(e => e.UseRange).HasDefaultValue(false);
        });

        modelBuilder.Entity<TblPayrollCodeRange>(entity =>
        {
            entity.Property(e => e.Commission)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_MoneyCommission");
            entity.Property(e => e.CommissionMode).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_CommissionMode");
            entity.Property(e => e.ExcludeRetainer).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_ExcludeRetainer");
            entity.Property(e => e.LowerLimit).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_LowerLimit");
            entity.Property(e => e.PayrollcodeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_PayrollcodeId");
            entity.Property(e => e.Retainer).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_Retainer");
            entity.Property(e => e.UpperLimit).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPayrollCodeRanges_UpperLimit");
        });

        modelBuilder.Entity<TblPension>(entity =>
        {
            entity.Property(e => e.PayrollcodeId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_PAYROLLCODE_ID");
            entity.Property(e => e.Basedon)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_PENSION_GROSS_1");
            entity.Property(e => e.Comments)
                .HasDefaultValue("-")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_COMMENTS");
            entity.Property(e => e.DeductNssfFrom).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_DEDUCT_NSSF_FROM");
            entity.Property(e => e.Employee).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_EMPLOYEE");
            entity.Property(e => e.Employer).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_EMPLOYER");
            entity.Property(e => e.ExemptEmployeeNssf).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_EXEMPT_EMPLOYEE_NSSF");
            entity.Property(e => e.PensionCode)
                .HasDefaultValue("-")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_PENSION_CODE");
            entity.Property(e => e.PensionId).HasComputedColumnSql("([PAYROLLCODE_ID])", false);
            entity.Property(e => e.PensionName)
                .HasDefaultValue("-")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_PENSION_NAME");
            entity.Property(e => e.PensionRate).HasAnnotation("Relational:DefaultConstraintName", "DF_tblPension_PENSION_RATE");
        });

        modelBuilder.Entity<TblPeriod>(entity =>
        {
            entity.Property(e => e.CompanyId)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriods_CompanyID");
        });

        modelBuilder.Entity<TblPeriodCompanyExpense>(entity =>
        {
            entity.Property(e => e.Amount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriodCompanyExpense_AMOUNT");
            entity.Property(e => e.EmployeeId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriodCompanyExpense_EMPLOYEE_ID");
            entity.Property(e => e.PayrollcodeId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriodCompanyExpense_PAYROLLCODE_ID");
            entity.Property(e => e.PeriodMonth)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriodCompanyExpense_PERIOD_MONTH");
            entity.Property(e => e.PeriodYear)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriodCompanyExpense_PERIOD_YEAR");
        });

        modelBuilder.Entity<TblPeriodTransaction>(entity =>
        {
            entity.Property(e => e.FormatId).HasDefaultValue(0);
            entity.Property(e => e.SourceAmount)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblPeriodTransactions_SourceAmount");
        });

        modelBuilder.Entity<TblRangeBenefit>(entity =>
        {
            entity.Property(e => e.RangeBenefitId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblRemuneration>(entity =>
        {
            entity.Property(e => e.CompanyId)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblRemuneration_COMPANY_ID");
        });

        modelBuilder.Entity<TblSendPayslip>(entity =>
        {
            entity.Property(e => e.EmailId).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<TblServiceCharge>(entity =>
        {
            entity.Property(e => e.PayrollcodeId)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblServiceCharge_payrollcode_id");
            entity.Property(e => e.Processed)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblServiceCharge_PROCESSED");
        });

        modelBuilder.Entity<TblServiceChargeDeduction>(entity =>
        {
            entity.Property(e => e.Recovered).HasAnnotation("Relational:DefaultConstraintName", "DF_tblServiceChargeDeductions_recovered");
            entity.Property(e => e.ServiceId).HasAnnotation("Relational:DefaultConstraintName", "DF_tblServiceChargeDeductions_SERVICE_ID");
        });

        modelBuilder.Entity<TblServiceEmployee>(entity =>
        {
            entity.Property(e => e.Collected)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tblServiceEmployee_COLLECTED");
            entity.Property(e => e.Processed).HasAnnotation("Relational:DefaultConstraintName", "DF_tblServiceEmployee_PROCESSED");
        });

        modelBuilder.Entity<TblUnusedRelief>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_tblUnusedRelief_1");
        });

        modelBuilder.Entity<TblVarTr>(entity =>
        {
            entity.Property(e => e.PayslipId).ValueGeneratedOnAdd();
            entity.Property(e => e.PrevAmount).HasDefaultValue(0m);
        });

        modelBuilder.Entity<ULogin>(entity =>
        {
            entity.Property(e => e.Logid).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<URole>(entity =>
        {
            entity.Property(e => e.Roleid).ValueGeneratedOnAdd();
        });

        modelBuilder.Entity<UUser1>(entity =>
        {
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Users_UserDeleted");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}