// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("OriginalSal")]
public partial class OriginalSal
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(50)]
    public string Period { get; set; }

    [Column(TypeName = "money")]
    public decimal? BasicPay { get; set; }

    [Column("HAllow", TypeName = "money")]
    public decimal? Hallow { get; set; }

    [Column("TAllow", TypeName = "money")]
    public decimal? Tallow { get; set; }

    [Column("LAllow", TypeName = "money")]
    public decimal? Lallow { get; set; }

    [Column("OAllow", TypeName = "money")]
    public decimal? Oallow { get; set; }

    [Column("Employee_id")]
    public long? EmployeeId { get; set; }
}