// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("pdContractTypes")]
public partial class PdContractType
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [StringLength(50)]
    public string Code { get; set; }

    [StringLength(50)]
    public string Description { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? DateFrom { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? DateTo { get; set; }

    [StringLength(50)]
    public string DoneBy { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? DateDone { get; set; }
}