// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("PositionRequirementsValue")]
public partial class PositionRequirementsValue
{
    [Column("PositionRequirementsValueID")]
    public int PositionRequirementsValueId { get; set; }

    [Column("PositionRequirementsID")]
    public int? PositionRequirementsId { get; set; }
    [Key]
    [Column("PositionID")]
    public int? PositionId { get; set; }

    [Column("PositionRequirementsValue")]
    [StringLength(100)]
    public string PositionRequirementsValue1 { get; set; }
}