// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("Prof")]
public partial class Prof
{
    [StringLength(20)]
    public string EmpCode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Course { get; set; }

    [Column("CFrom", TypeName = "smalldatetime")]
    public DateTime? Cfrom { get; set; }

    [Column("CTo", TypeName = "smalldatetime")]
    public DateTime? Cto { get; set; }
    [Key]
    [Column("ELevel")]
    [StringLength(200)]
    public string Elevel { get; set; }

    [StringLength(200)]
    public string Award { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}