// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("RefSource")]
public partial class RefSource
{
    [Key]
    [Column("NCode")]
    [StringLength(20)]
    public string Ncode { get; set; }

    [Column("PCode")]
    [StringLength(20)]
    public string Pcode { get; set; }

    [StringLength(200)]
    public string Name { get; set; }

    [Column("dDate", TypeName = "smalldatetime")]
    public DateTime? DDate { get; set; }
}