// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("Review")]
public partial class Review
{
    [Key]
    [Column("NCode")]
    [StringLength(20)]
    public string Ncode { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [Column("TDate", TypeName = "smalldatetime")]
    public DateTime? Tdate { get; set; }

    [Column("TTime")]
    [StringLength(50)]
    public string Ttime { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [StringLength(200)]
    public string Comments { get; set; }
}