// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("SalaryIncrease")]
public partial class SalaryIncrease
{
    [Key]   
    [Column("id")]
    public long Id { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }

    [Column("test")]
    [StringLength(50)]
    [Unicode(false)]
    public string Test { get; set; }

    [StringLength(50)]
    public string Empcode { get; set; }

    [Column("period")]
    [StringLength(10)]
    [Unicode(false)]
    public string Period { get; set; }

    [StringLength(20)]
    public string IncreaseType { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? BasicPay { get; set; }

    [Column("HAllow", TypeName = "numeric(18, 0)")]
    public decimal? Hallow { get; set; }

    [Column("TAllow", TypeName = "numeric(18, 0)")]
    public decimal? Tallow { get; set; }

    [Column("LAllow", TypeName = "numeric(18, 0)")]
    public decimal? Lallow { get; set; }

    [Column("OAllow", TypeName = "numeric(18, 0)")]
    public decimal? Oallow { get; set; }
}