// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("security")]
public partial class Security
{
    [Column("id")]
    public int Id { get; set; }

    [Column("UID")]
    [StringLength(50)]
    public string Uid { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    [Column("GNo")]
    [StringLength(50)]
    public string Gno { get; set; }

    [StringLength(50)]
    public string Pass { get; set; }

    public short? Exc { get; set; }

    [StringLength(50)]
    public string Excc { get; set; }

    [Column("UUser")]
    [StringLength(50)]
    public string Uuser { get; set; }

    [Column("TTime", TypeName = "datetime")]
    public DateTime? Ttime { get; set; }

    [Column("EDate", TypeName = "datetime")]
    public DateTime? Edate { get; set; }

    [StringLength(120)]
    public string Terms { get; set; }

    [Column("DName")]
    [StringLength(120)]
    public string Dname { get; set; }

    [Column("LCode")]
    [StringLength(120)]
    public string Lcode { get; set; }

    [StringLength(50)]
    public string SubSystem { get; set; }

    [StringLength(50)]
    public string Machine { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? LoginTime { get; set; }

    [Column("LogOut_Time", TypeName = "datetime")]
    public DateTime? LogOutTime { get; set; }

    [StringLength(50)]
    public string EmpCode { get; set; }

    [StringLength(50)]
    public string EmpName { get; set; }

    [StringLength(50)]
    public string DeptCode { get; set; }

    [StringLength(50)]
    public string DeptName { get; set; }

    public bool? Frozen { get; set; }

    [Column("Reason_Frozen")]
    [StringLength(50)]
    public string ReasonFrozen { get; set; }

    [Column("Frozen_Count")]
    public int? FrozenCount { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string CategoryAccess { get; set; }

    [Column("employee_id")]
    public int? EmployeeId { get; set; }
}