// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("semp")]
public partial class Semp
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("SCode")]
    [StringLength(20)]
    public string Scode { get; set; }

    [Column("LCode")]
    [StringLength(20)]
    public string Lcode { get; set; }

    [StringLength(20)]
    public string EmpCode { get; set; }

    [Column("HOD")]
    public bool? Hod { get; set; }

    [Column("DCode")]
    [StringLength(50)]
    public string Dcode { get; set; }

    [Column("employee_id")]
    public int EmployeeId { get; set; }

    [Column("cstructure_id")]
    public int? CstructureId { get; set; }
}