// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("SReports")]
public partial class Sreport
{
    [StringLength(200)]
    public string LinkCode { get; set; }

    [StringLength(20)]
    public string PreviousCode { get; set; }

    public int? MyLevel { get; set; }

    [StringLength(20)]
    public string Code { get; set; }

    [StringLength(200)]
    public string Description { get; set; }
    [Key]
    [Column("ObjectID")]
    [StringLength(200)]
    public string ObjectId { get; set; }

    [Column("RFilter")]
    [StringLength(50)]
    public string Rfilter { get; set; }

    [StringLength(50)]
    public string Subsystem { get; set; }
}