// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblAllowance")]
public partial class TblAllowance
{
    [Key]
    [Column("ALLOWANCE_ID")]
    public int AllowanceId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("ALLOWANCE_CODE")]
    [StringLength(50)]
    public string AllowanceCode { get; set; }

    [Column("ALLOWANCE_NAME")]
    [StringLength(50)]
    public string AllowanceName { get; set; }

    [Column("AMOUNT")]
    [StringLength(50)]
    public string Amount { get; set; }
}