// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblAccountLayout")]
public partial class TblAccountLayout
{
    [Key]
    [Column("ACCOUNTID")]
    public int Accountid { get; set; }

    [Required]
    [Column("ACCOUNT_NUMBER")]
    [StringLength(50)]
    public string AccountNumber { get; set; }

    [Column("ACCOUNT_DESCRIPTION")]
    [StringLength(50)]
    public string AccountDescription { get; set; }

    [Column("NORMAL_BALANCE")]
    public int NormalBalance { get; set; }

    [Column("SUSPENSE")]
    public bool Suspense { get; set; }
}