// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblBankTransfer")]
public partial class TblBankTransfer
{
    [Key]
    [Column("SFI_HEADER", TypeName = "ntext")]
    public string SfiHeader { get; set; }

    [Column("SFI_BODY", TypeName = "ntext")]
    public string SfiBody { get; set; }

    [Column("SFI_FOOTER", TypeName = "ntext")]
    public string SfiFooter { get; set; }
}