// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblBonusDetail")]
public partial class TblBonusDetail
{
    [Key]
    [Column("BONUSDETAIL_ID")]
    public int BonusdetailId { get; set; }

    [Column("BONUS_ID")]
    public int? BonusId { get; set; }

    [Column("LOWER_LIMIT")]
    public double? LowerLimit { get; set; }

    [Column("UPPER_LIMIT")]
    public double? UpperLimit { get; set; }

    [Column("DETAIL_VALUE")]
    public double? DetailValue { get; set; }
}