// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblBankBranches")]
public partial class TblBankBranch1
{
    [StringLength(50)]
    public string BankCode { get; set; }

    [StringLength(50)]
    public string BranchCode { get; set; }

    [StringLength(50)]
    public string BranchName { get; set; }
}