// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblBonus")]
public partial class TblBonu
{
    [Key]
    [Column("BONUS_ID")]
    public int BonusId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("BONUS_CODE")]
    [StringLength(50)]
    public string BonusCode { get; set; }

    [Column("BONUS_NAME")]
    [StringLength(50)]
    public string BonusName { get; set; }

    [Column("MONTHLY")]
    public bool Monthly { get; set; }

    [Column("YEARLY")]
    public bool Yearly { get; set; }

    [Column("RATE_BASED")]
    public bool RateBased { get; set; }

    [Column("AMOUNT_BASED")]
    public bool AmountBased { get; set; }
}