// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblBank")]
public partial class TblBank
{
    [Key]
    [Column("BANK_ID")]
    public int BankId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("BANK_CODE")]
    [StringLength(50)]
    public string BankCode { get; set; }

    [Column("BANK_NAME")]
    [StringLength(250)]
    public string BankName { get; set; }

    [Column("BANK_COMMENTS", TypeName = "ntext")]
    public string BankComments { get; set; }
}