// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCasualPaymentCriteria")]
public partial class TblCasualPaymentCriterion
{
    [Key]
    [Column("CRITERIA_ID")]
    public int CriteriaId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("CRITERIA_CODE")]
    [StringLength(50)]
    public string CriteriaCode { get; set; }

    [Column("CRITERIA_NAME")]
    [StringLength(50)]
    public string CriteriaName { get; set; }

    [Column("CRITERIA_COMMENTS")]
    [StringLength(100)]
    public string CriteriaComments { get; set; }
}