// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblCompanyPaymentSummary")]
public partial class TblCompanyPaymentSummary
{
    public int Id { get; set; }

    public int CompanyId { get; set; }
    [Key]
    [Column(TypeName = "money")]
    public decimal CashTotals { get; set; }

    [Column(TypeName = "money")]
    public decimal CashNumbers { get; set; }

    [Column(TypeName = "money")]
    public decimal BankTotals { get; set; }
    
    [Column(TypeName = "money")]
    public decimal BankNumbers { get; set; }

    [Column(TypeName = "money")]
    public decimal ChequeTotals { get; set; }

    [Column(TypeName = "money")]
    public decimal ChequeNumbers { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? CreatedOn { get; set; }
}