// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblControl")]
public partial class TblControl
{
    [Key]
    [Column("CONTROL_ID")]
    public int ControlId { get; set; }

    [Column("MODULE_ID")]
    public int? ModuleId { get; set; }

    [Column("CONTROL_TAG")]
    [StringLength(50)]
    public string ControlTag { get; set; }

    [Column("CONTROL_NAME")]
    [StringLength(50)]
    public string ControlName { get; set; }

    [Column("CONTROL_TYPE")]
    [StringLength(50)]
    public string ControlType { get; set; }
}