// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCostcenterRemuneration")]
public partial class TblCostcenterRemuneration
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("COSTCENTER_ID")]
    public int? CostcenterId { get; set; }

    [Column("REMUNERATION_ID")]
    public int? RemunerationId { get; set; }

    [Column("ISAMOUNT")]
    public bool? Isamount { get; set; }

    [Column("AMOUNT_VALUE", TypeName = "money")]
    public decimal? AmountValue { get; set; }

    [Column("FORMULA")]
    [StringLength(100)]
    public string Formula { get; set; }
}