// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCompanyBank")]
public partial class TblCompanyBank
{
    [Key]
    [Column("COMPANYBANK_ID")]
    public int CompanybankId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("BANKBRANCH_ID")]
    public int? BankbranchId { get; set; }

    [Column("ACCOUNT_NUMBER")]
    [StringLength(100)]
    public string AccountNumber { get; set; }

    [Column("DEFAULT_BANK")]
    public bool DefaultBank { get; set; }
}