// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblCasualEmployeeTransactions")]
public partial class TblCasualEmployeeTransaction
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("REMUNERATION_ID")]
    public int? RemunerationId { get; set; }

    [Column("UNITS")]
    public double? Units { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("PERIOD_DATE")]
    public int? PeriodDate { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("TRANSACTION_DATE", TypeName = "smalldatetime")]
    public DateTime? TransactionDate { get; set; }

    [Column("PROCESSED")]
    public bool? Processed { get; set; }

    [Column("PAID")]
    public bool? Paid { get; set; }

    [Column("PAYMENT_DATE", TypeName = "smalldatetime")]
    public DateTime? PaymentDate { get; set; }

    [Column("USER_ID")]
    public int? UserId { get; set; }
}