// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblDefinedBenefits")]
public partial class TblDefinedBenefit
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("BENEFIT_CODE")]
    [StringLength(50)]
    public string BenefitCode { get; set; }

    [Column("BENEFIT_NAME")]
    [StringLength(50)]
    public string BenefitName { get; set; }

    [Column("URBAN_RATE", TypeName = "money")]
    public decimal? UrbanRate { get; set; }

    [Column("AGRICULTURAL_RATE", TypeName = "money")]
    public decimal? AgriculturalRate { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("ISAMOUNT")]
    public bool? Isamount { get; set; }
}