// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblDenomination")]
public partial class TblDenomination
{
    [Key]
    [Column("DENOMINATION_ID")]
    public int DenominationId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("DENOMINATION_NAME")]
    [StringLength(50)]
    public string DenominationName { get; set; }

    [Column("DENOMINATION_VALUE")]
    public double? DenominationValue { get; set; }
}