// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblDailyTransactions")]
public partial class TblDailyTransaction
{
    [Key]
    public int DailyTransactionId { get; set; }

    public int? EmployeeId { get; set; }

    [Column("PayrollCodeID")]
    public int? PayrollCodeId { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? DateWorked { get; set; }

    [Column(TypeName = "money")]
    public decimal? Amount { get; set; }

    [StringLength(200)]
    public string PayrollCodeName { get; set; }

    [Column(TypeName = "money")]
    public decimal? ResultAmount { get; set; }

    [StringLength(200)]
    public string ResultPayRollCodeName { get; set; }

    public int? CompanyId { get; set; }

    public int? PeriodMonth { get; set; }

    public int? PeriodYear { get; set; }
}