// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeCasualPaymentCriteria")]
public partial class TblEmployeeCasualPaymentCriterion
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EMP_ID")]
    public int? EmpId { get; set; }

    [Column("CRITERIA_ID")]
    public int? CriteriaId { get; set; }
}