// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeTransactions")]
public partial class TblEmployeeTransaction
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("Employee_Id")]
    public int? EmployeeId { get; set; }

    [StringLength(255)]
    public string EmpCode { get; set; }

    [Column("PayrollCode_Id")]
    public int? PayrollCodeId { get; set; }

    [StringLength(50)]
    public string Payrollcode { get; set; }

    [Column("Payrollcode_Name")]
    [StringLength(255)]
    public string PayrollcodeName { get; set; }

    public double? Amount { get; set; }

    [Column("Currency_Id")]
    public int? CurrencyId { get; set; }

    [Column("Period_Month")]
    public int? PeriodMonth { get; set; }

    [Column("Period_Year")]
    public int? PeriodYear { get; set; }

    [Column("BALANCE")]
    public int? Balance { get; set; }

    [Column("Date_Transaction", TypeName = "datetime")]
    public DateTime? DateTransaction { get; set; }

    public int? FormatId { get; set; }

    public bool? IsRangeBenefit { get; set; }
}