// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeBasicSalary")]
public partial class TblEmployeeBasicSalary
{
    [Key]
    [Column("BASICSALARY_ID")]
    public int BasicsalaryId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("BASIC_SALARY1")]
    public int? BasicSalary1 { get; set; }

    [Column("BASIC_SALARY2")]
    public int? BasicSalary2 { get; set; }

    [Column("BASIC_SALARY3")]
    public int? BasicSalary3 { get; set; }

    [Column("BASIC_SALARY4")]
    public int? BasicSalary4 { get; set; }

    [Column("BASIC_SALARY5")]
    public int? BasicSalary5 { get; set; }

    [Column("BASIC_SALARY6")]
    public int? BasicSalary6 { get; set; }

    [Column("BASIC_SALARY7")]
    public int? BasicSalary7 { get; set; }

    [Column("BASIC_SALARY8")]
    public int? BasicSalary8 { get; set; }

    [Column("BASIC_SALARY9")]
    public int? BasicSalary9 { get; set; }

    [Column("BASIC_SALARY10")]
    public int? BasicSalary10 { get; set; }

    [Column("BASIC_SALARY11")]
    public int? BasicSalary11 { get; set; }

    [Column("BASIC_SALARY12")]
    public int? BasicSalary12 { get; set; }

    [Column("PREVIOUS_BASIC_SALARY")]
    public int? PreviousBasicSalary { get; set; }

    [Column("BASIC_SALARY")]
    public double? BasicSalary { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("CASH")]
    public bool? Cash { get; set; }

    [Column("CHEQUE")]
    public bool? Cheque { get; set; }

    [Column("BANK_TRANSFER")]
    public bool? BankTransfer { get; set; }

    [Column("HOURLY")]
    public bool? Hourly { get; set; }

    [Column("DAILY")]
    public bool? Daily { get; set; }

    [Column("WEEKLY")]
    public bool? Weekly { get; set; }

    [Column("MONTHLY")]
    public bool? Monthly { get; set; }

    [Column("NSSF")]
    public bool? Nssf { get; set; }

    [Column("NSSF_AMOUNT")]
    public double? NssfAmount { get; set; }

    [Column("EMPLOYER_NSSF")]
    public double? EmployerNssf { get; set; }

    [Column("PAYE")]
    public bool? Paye { get; set; }

    [Column("NHIF")]
    public bool? Nhif { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("CURRENT_PAY")]
    public bool? CurrentPay { get; set; }

    [Column("OVERWRITENSSF")]
    public bool? Overwritenssf { get; set; }

    [Column("OVERWRITENHIF")]
    public bool? Overwritenhif { get; set; }

    [Column("OVERWRITEPAYE")]
    public bool? Overwritepaye { get; set; }
}