// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblEmployeeCooperative")]
public partial class TblEmployeeCooperative
{
    [Column("EMPCOOP_ID")]
    public int EmpcoopId { get; set; }

    [Column("COOP_ID")]
    public int? CoopId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("SACCO_NUMBER")]
    [StringLength(50)]
    public string SaccoNumber { get; set; }

    [Column("BASIC_PAY")]
    public bool BasicPay { get; set; }

    [Column("GROSS_PAY")]
    public bool GrossPay { get; set; }

    [Column("DATE_JOINED", TypeName = "smalldatetime")]
    public DateTime? DateJoined { get; set; }

    [Column("DATE_EXPIRY", TypeName = "smalldatetime")]
    public DateTime? DateExpiry { get; set; }

    [Column("EMPLOYEE")]
    public double? Employee { get; set; }

    [Column("CURRENT_AMOUNT")]
    public double? CurrentAmount { get; set; }

    [Column("RATE_BASED")]
    public bool RateBased { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }
}