// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeInsurance")]
public partial class TblEmployeeInsurance
{
    [Key]
    [Column("EMPLOYEEPOLICY_ID")]
    public int EmployeepolicyId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("INS_ID")]
    public int? InsId { get; set; }

    [Column("POLICY_ID")]
    public int? PolicyId { get; set; }

    [Column("PREMIUM_AMOUNT")]
    public double? PremiumAmount { get; set; }

    [Column("RELIEF_RATE")]
    public double? ReliefRate { get; set; }

    [Column("RELIEF_AMOUNT")]
    public double? ReliefAmount { get; set; }

    [Column("START_DATE", TypeName = "smalldatetime")]
    public DateTime? StartDate { get; set; }

    [Column("END_DATE", TypeName = "smalldatetime")]
    public DateTime? EndDate { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("POLICY_NO")]
    [StringLength(50)]
    public string PolicyNo { get; set; }
}