// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeMotorcars")]
public partial class TblEmployeeMotorcar
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("MOTOR_ID")]
    public int? MotorId { get; set; }

    [Column("VEHICLE_REGNO")]
    [StringLength(100)]
    public string VehicleRegno { get; set; }

    [Column("ACTUAL_COST", TypeName = "money")]
    public decimal? ActualCost { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }
}