// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeLoan")]
public partial class TblEmployeeLoan
{
    [Key]
    [Column("EMPLOYEELOAN_ID")]
    public int EmployeeloanId { get; set; }

    [Column("COOP_ID")]
    public int? CoopId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("LOAN_ID")]
    public int? LoanId { get; set; }

    [Column("ISSUE_DATE", TypeName = "smalldatetime")]
    public DateTime? IssueDate { get; set; }

    [Column("REFRENCE_NO")]
    [StringLength(50)]
    public string RefrenceNo { get; set; }

    [Column("START_DATE", TypeName = "smalldatetime")]
    public DateTime? StartDate { get; set; }

    [Column("START_MONTH")]
    public int? StartMonth { get; set; }

    [Column("START_YEAR")]
    public int? StartYear { get; set; }

    [Column("END_DATE", TypeName = "smalldatetime")]
    public DateTime? EndDate { get; set; }

    [Column("END_MONTH")]
    public int? EndMonth { get; set; }

    [Column("END_YEAR")]
    public int? EndYear { get; set; }

    [Column("LOAN_AMOUNT", TypeName = "money")]
    public decimal? LoanAmount { get; set; }

    [Column("RECOVERY_AMOUNT", TypeName = "money")]
    public decimal? RecoveryAmount { get; set; }

    [Column("CURRENT_AMOUNT", TypeName = "money")]
    public decimal? CurrentAmount { get; set; }

    [Column("LOANSUSPENDED")]
    public bool? Loansuspended { get; set; }

    [Column("RECOVER_INTEREST_ON_SUSPENSION")]
    public bool? RecoverInterestOnSuspension { get; set; }

    [Column("SUSPENSION_COMMENTS", TypeName = "ntext")]
    public string SuspensionComments { get; set; }

    [Column("COMMENTS", TypeName = "ntext")]
    public string Comments { get; set; }

    [Column("ACTIVATION_DATE", TypeName = "smalldatetime")]
    public DateTime? ActivationDate { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("INTEREST_STARTDATE", TypeName = "datetime")]
    public DateTime? InterestStartdate { get; set; }

    [Column("INTEREST_RECOVERY")]
    [StringLength(50)]
    public string InterestRecovery { get; set; }

    [Column("BALANCE", TypeName = "money")]
    public decimal? Balance { get; set; }

    [Column("TRANSACTIONDATE", TypeName = "smalldatetime")]
    public DateTime? Transactiondate { get; set; }
}