// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[PrimaryKey("PensionId", "EmployeeId")]
[Table("tblEmployeePension")]
public partial class TblEmployeePension
{
   [Key]
    [Column("EMPPENSION_ID")]
    public int EmppensionId { get; set; }

    [Key]
    [Column("PENSION_ID")]
    public int PensionId { get; set; }

    [Key]
    [Column("EMPLOYEE_ID")]
    public int EmployeeId { get; set; }

    [Column("PENSION_NO")]
    [StringLength(50)]
    [Unicode(false)]
    public string PensionNo { get; set; }

    [Column("MANUALDEDUCTION", TypeName = "money")]
    public decimal? Manualdeduction { get; set; }

    [Column("BALANCE_CWD", TypeName = "money")]
    public decimal? BalanceCwd { get; set; }

    [Column("EMPLOYERMANUALDEDUCTION", TypeName = "money")]
    public decimal? Employermanualdeduction { get; set; }

    [Column("EMPLOYERBALANCE_CWD", TypeName = "money")]
    public decimal? EmployerbalanceCwd { get; set; }

    [Column("START_MONTH")]
    public int? StartMonth { get; set; }

    [Column("START_YEAR")]
    public int? StartYear { get; set; }

    [Column("ACTIVE")]
    public bool? Active { get; set; }
}