// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblEmployees")]
public partial class TblEmployee
{
    public int EmployeeId { get; set; }

    [Column("employee_id")]
    public int? EmployeeId1 { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string SurName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string OtherNames { get; set; }

    [StringLength(24)]
    [Unicode(false)]
    public string IdNo { get; set; }

    [Column("HAddress")]
    [StringLength(100)]
    [Unicode(false)]
    public string Haddress { get; set; }

    [Column("HTel")]
    [StringLength(100)]
    [Unicode(false)]
    public string Htel { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string PayrollNo { get; set; }

    [Column("PINNo")]
    [StringLength(100)]
    [Unicode(false)]
    public string Pinno { get; set; }

    [Column("OBasicPay", TypeName = "money")]
    public decimal? ObasicPay { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BankCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BankName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BankBranch { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string BankBranchName { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string AccountNo { get; set; }
}