// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeePayrollCode")]
public partial class TblEmployeePayrollCode
{
    [Key]
    [Column("EMPLOYEECODE_ID")]
    public long EmployeecodeId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("EMPCODE")]
    [StringLength(50)]
    public string Empcode { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("OBALANCE")]
    public int? Obalance { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("HASENDDATE")]
    public bool? Hasenddate { get; set; }

    [Column("ENDDATE", TypeName = "datetime")]
    public DateTime? Enddate { get; set; }

    public int? FormatId { get; set; }

    public bool? IsRangeBenefit { get; set; }
}