// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeBankNetPay")]
public partial class TblEmployeeBankNetPay
{
    [Key]
    [Column("NETPAY_ID")]
    public int NetpayId { get; set; }

    [Column("EMPLOYEEBANK_ID")]
    public int? EmployeebankId { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("COMPANYBANK_ID")]
    public int? CompanybankId { get; set; }

    [Column(TypeName = "money")]
    public decimal? Reimbursement { get; set; }
}