// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeHousing")]
public partial class TblEmployeeHousing
{
    [Key]
    [Column("EMPHOUSING_ID")]
    public int EmphousingId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("HOUSING_ID")]
    public int? HousingId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("RENT")]
    public double? Rent { get; set; }

    [Column("ACCOMODATION")]
    public bool Accomodation { get; set; }

    [Column("EMPLOYER")]
    public bool Employer { get; set; }

    [Column("PAYSLIP")]
    public bool Payslip { get; set; }
}