// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeMessage")]
public partial class TblEmployeeMessage
{
    [Key]
    [Column("MESSAGE_ID")]
    public int MessageId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("MESSAGE1")]
    [StringLength(30)]
    public string Message1 { get; set; }

    [Column("MESSAGE2")]
    [StringLength(30)]
    public string Message2 { get; set; }

    [Column("MESSAGE3")]
    [StringLength(30)]
    public string Message3 { get; set; }

    [Column("MESSAGE4")]
    [StringLength(30)]
    public string Message4 { get; set; }

    [Column("DELETE_NO")]
    public bool DeleteNo { get; set; }
}