// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeePeriodDetails")]
public partial class TblEmployeePeriodDetail
{
    [Key]
    [Column("EMPLOYEEPAY_ID")]
    public int EmployeepayId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("GRADE_ID")]
    public int? GradeId { get; set; }

    [Column("CSTRUCTURE_ID")]
    public int? CstructureId { get; set; }

    [Column("DESIGNATION_ID")]
    public int? DesignationId { get; set; }

    [Column("BASIC_PAY", TypeName = "money")]
    public decimal? BasicPay { get; set; }

    [Column("HOUSE_ALLOWANCE", TypeName = "money")]
    public decimal? HouseAllowance { get; set; }

    [Column("ALLOWANCES", TypeName = "money")]
    public decimal? Allowances { get; set; }

    [Column("BENEFITS", TypeName = "money")]
    public decimal? Benefits { get; set; }

    [Column("VALUEOFQUARTERS", TypeName = "money")]
    public decimal? Valueofquarters { get; set; }

    [Column("OOINTEREST", TypeName = "money")]
    public decimal? Oointerest { get; set; }

    [Column("DEFINECONTRIBUTION", TypeName = "money")]
    public decimal? Definecontribution { get; set; }

    [Column("GROSS_PAY", TypeName = "money")]
    public decimal? GrossPay { get; set; }

    [Column("TAXABLE_PAY", TypeName = "money")]
    public decimal? TaxablePay { get; set; }

    [Column("TAX_CHARGED", TypeName = "money")]
    public decimal? TaxCharged { get; set; }

    [Column("INSURANCE_RELIEF", TypeName = "money")]
    public decimal? InsuranceRelief { get; set; }

    [Column("RELIEF", TypeName = "money")]
    public decimal? Relief { get; set; }

    [Column("PAYE", TypeName = "money")]
    public decimal? Paye { get; set; }

    [Column("NSSF", TypeName = "money")]
    public decimal? Nssf { get; set; }

    [Column("NHIF", TypeName = "money")]
    public decimal? Nhif { get; set; }

    [Column("DEDUCTION", TypeName = "money")]
    public decimal? Deduction { get; set; }

    [Column("NET_PAY", TypeName = "money")]
    public decimal? NetPay { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }
}