// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeBasicPayArrears")]
public partial class TblEmployeeBasicPayArrear
{
    [Key]
    [Column("EMPLOYEEPAY_ID")]
    public int EmployeepayId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("BASIC_PAY_ARREARS")]
    public double? BasicPayArrears { get; set; }

    [Column("OTHER_ALLOWANCES")]
    public double? OtherAllowances { get; set; }

    [Column("PAYEARREARS")]
    public double? Payearrears { get; set; }

    [Column("DEDUCTION_ARREARS")]
    public double? DeductionArrears { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }
}