// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblEmployeeType")]
public partial class TblEmployeeType
{
    [Key]
    [Column("EMPTYPE_ID")]
    public int EmptypeId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("EMPTYPE_CODE")]
    [StringLength(50)]
    public string EmptypeCode { get; set; }

    [Column("EMPTYPE_NAME")]
    [StringLength(50)]
    public string EmptypeName { get; set; }
}