// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblFringeBenefitTax")]
public partial class TblFringeBenefitTax
{
    [Key]
    [Column("FRINGEBENEFIT_ID")]
    public int FringebenefitId { get; set; }

    [Column("MARKET_RATE")]
    public double? MarketRate { get; set; }

    [Column("CORP_RATE")]
    public double? CorpRate { get; set; }
}