// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblFormatCostCenters")]
public partial class TblFormatCostCenter
{
    [Key]
    public int FormatCostCenterId { get; set; }

    public int FormatId { get; set; }

    [Column("CostcenterID")]
    public int CostcenterId { get; set; }
}