// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblGroupControl")]
public partial class TblGroupControl
{
    [Column("CONTROL_ID")]
    public int? ControlId { get; set; }

    [Column("GROUP_ID")]
    public int? GroupId { get; set; }

    [Column("ALLOW_ACCESS")]
    public bool AllowAccess { get; set; }
}