// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblHousingScheme")]
public partial class TblHousingScheme
{
    [Key]
    [Column("HOUSING_ID")]
    public int HousingId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("HOUSING_CODE")]
    [StringLength(50)]
    public string HousingCode { get; set; }

    [Column("HOUSING_NAME")]
    [StringLength(50)]
    public string HousingName { get; set; }

    [Column("MARKET_VALUE")]
    public double? MarketValue { get; set; }

    [Column("RENT_VALUE")]
    public double? RentValue { get; set; }

    [Column("EMPLOYER")]
    public bool Employer { get; set; }
}