// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblHomeOwnershipSavingsPlan")]
public partial class TblHomeOwnershipSavingsPlan
{
    [Key]
    [Column("Plan_Id")]
    public int PlanId { get; set; }

    [Column(TypeName = "money")]
    public decimal? MaxMonthlyDeduction { get; set; }

    public bool BenefitsOnly { get; set; }
}