// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblHousing")]
public partial class TblHousing
{
    [Key]
    [Column("Housing_ID")]
    public int HousingId { get; set; }

    public int? NormalPerTaxablePay { get; set; }

    public int? AgruculturalPerTaxablePay { get; set; }

    [Column(TypeName = "money")]
    public decimal? UpperLimit { get; set; }

    public int? Rounding { get; set; }
}