// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblJV")]
public partial class TblJv
{
    [Key]
    [Column("JVID")]
    public int Jvid { get; set; }

    [Column("PayrollCode_Id")]
    public int? PayrollCodeId { get; set; }

    [Column("Account_No")]
    [StringLength(50)]
    public string AccountNo { get; set; }

    [StringLength(2)]
    public string TransType { get; set; }

    [Column("Section_Id")]
    public int? SectionId { get; set; }

    [Column("Section_Name")]
    [StringLength(50)]
    public string SectionName { get; set; }

    [Column("Period_Month")]
    public int? PeriodMonth { get; set; }

    [Column("Period_Year")]
    public int? PeriodYear { get; set; }
}