// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblLoanReduction")]
public partial class TblLoanReduction
{
    [Key]
    [Column("REDUCTION_ID")]
    public int ReductionId { get; set; }

    [Column("EMPLOYEELOAN_ID")]
    public int? EmployeeloanId { get; set; }

    [Column("REDUCTION_DATE", TypeName = "smalldatetime")]
    public DateTime? ReductionDate { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("REFRENCE_NUMBER")]
    [StringLength(50)]
    public string RefrenceNumber { get; set; }

    [Column("COMMENTS", TypeName = "ntext")]
    public string Comments { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }
}