// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblLoanAdjustments")]
public partial class TblLoanAdjustment
{
    [Key]
    public int LoanAdjustmentId { get; set; }

    public int? EmployeeLoanId { get; set; }

    [Column(TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("periodMonth")]
    public int? PeriodMonth { get; set; }

    [Column("periodYear")]
    public int? PeriodYear { get; set; }

    [StringLength(100)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(100)]
    public string ModifiedBy { get; set; }
}