// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblLoanTransaction")]
public partial class TblLoanTransaction
{
    [Key]
    [Column("LOANTRANS_ID")]
    public int LoantransId { get; set; }

    [Column("EMPLOAN_ID")]
    public int? EmploanId { get; set; }

    [Column("AMOUNT_PAID", TypeName = "money")]
    public decimal? AmountPaid { get; set; }

    [Column("INTEREST_PAID", TypeName = "money")]
    public decimal? InterestPaid { get; set; }

    [Column("AMOUNT_DUE", TypeName = "money")]
    public decimal? AmountDue { get; set; }

    [Column("FINANCED_AMOUNT", TypeName = "money")]
    public decimal? FinancedAmount { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("day_entered")]
    public int? DayEntered { get; set; }

    [Column("month_entered")]
    public int? MonthEntered { get; set; }

    [Column("year_entered")]
    public int? YearEntered { get; set; }

    [Column("PAYSLIP_TRANS")]
    public bool? PayslipTrans { get; set; }

    [Column("COMMENTS")]
    [StringLength(255)]
    public string Comments { get; set; }
}