// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblMailSetUp")]
public partial class TblMailSetUp
{
    [Key]
    public int MailsetUpId { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmailAddress { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmailPassword { get; set; }

    [Column("SMTPClientName")]
    [StringLength(100)]
    [Unicode(false)]
    public string SmtpclientName { get; set; }

    [Column("SMTPPort")]
    [StringLength(100)]
    [Unicode(false)]
    public string Smtpport { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? CreatedOn { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? ModifiedOn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ModifiedBy { get; set; }
}