// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblNonPayrollTransactions")]
public partial class TblNonPayrollTransaction
{
    [Key]
    public int NonPayrollTransId { get; set; }

    public int EmployeeId { get; set; }

    public int PayrollCodeId { get; set; }

    public int PeriodMonth { get; set; }

    public int PeriodYear { get; set; }

    [Required]
    [StringLength(50)]
    public string Description { get; set; }

    [Required]
    [StringLength(50)]
    public string ReceiptNo { get; set; }

    public int UserId { get; set; }

    [Required]
    [StringLength(50)]
    public string TransType { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TransDate { get; set; }

    [Column(TypeName = "money")]
    public decimal Amount { get; set; }
}