// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblOwnerOccupiedInterest")]
public partial class TblOwnerOccupiedInterest
{
    [Key]
    [Column("OwnerOcuupied_Id")]
    public int OwnerOcuupiedId { get; set; }

    [Column(TypeName = "money")]
    public decimal? MaxMonthlyInterest { get; set; }

    [Column(TypeName = "money")]
    public decimal? DecDeduction { get; set; }

    public bool OnlyBenefits { get; set; }
}