// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblOtherOptions")]
public partial class TblOtherOption
{
    public bool? ShowPrinterSetup { get; set; }

    public bool? BlockPostingForLeave { get; set; }

    [Column("NHIFOption")]
    [StringLength(20)]
    public string Nhifoption { get; set; }

    public double? InsurancePercentage { get; set; }

    [Column(TypeName = "money")]
    public decimal? MaximumInsuranceRelief { get; set; }

    [Column("DonotCarryForwardURelief")]
    public bool? DonotCarryForwardUrelief { get; set; }

    public bool? HideInPayslip { get; set; }

    public bool? HideTaxCharged { get; set; }
}