// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblOptions")]
public partial class TblOption
{
    [Column("Cash_PaymentRounding")]
    public int? CashPaymentRounding { get; set; }

    [Column("Bank_TransferRounding")]
    public int? BankTransferRounding { get; set; }

    public bool LeapYearTakenAs366 { get; set; }

    [Column("SaveJV")]
    public bool SaveJv { get; set; }

    [Column("YTDStatsOnPayslip")]
    public bool YtdstatsOnPayslip { get; set; }

    public int? PayslipFormats { get; set; }

    [StringLength(50)]
    public string RoundingMode { get; set; }

    [Column("ROUNDING_PAYMENT_ID")]
    public int? RoundingPaymentId { get; set; }

    [Column("ROUNDING_PAYMENT_DESCRIPTION")]
    [StringLength(50)]
    public string RoundingPaymentDescription { get; set; }

    [Column("ROUNDING_DEDUCTION_ID")]
    public int? RoundingDeductionId { get; set; }

    [Column("ROUNDING_DEDUCTION_DESCRIPTION")]
    [StringLength(50)]
    public string RoundingDeductionDescription { get; set; }

    [Column("NETPAY_ROUNDING_CRITERIA")]
    [StringLength(10)]
    [Unicode(false)]
    public string NetpayRoundingCriteria { get; set; }

    [Column("PENSION_DEDUCTION_ID")]
    public int? PensionDeductionId { get; set; }

    [Column("PENSION_DESCRIPTION")]
    [StringLength(50)]
    public string PensionDescription { get; set; }

    [Column("USE_PREVIOUS_SALARY")]
    public bool? UsePreviousSalary { get; set; }

    [Column("PREVIOUS_PENSION_ID")]
    public int? PreviousPensionId { get; set; }

    [Column("PREVIOUS_PENSION_DESCRIPTION")]
    [StringLength(50)]
    public string PreviousPensionDescription { get; set; }

    [Column("PAYE_ROUNDING")]
    public double? PayeRounding { get; set; }

    [Column("PAYE_ROUNDING_CRITERIA")]
    [StringLength(10)]
    [Unicode(false)]
    public string PayeRoundingCriteria { get; set; }

    [Column("CARRY_FORWARD_OVERDRAWN")]
    public bool? CarryForwardOverdrawn { get; set; }

    [Column("OVERDRAWN_ID")]
    public int? OverdrawnId { get; set; }

    [Column("OVERDRAWN_DESCRIPTION")]
    [StringLength(50)]
    public string OverdrawnDescription { get; set; }

    [Column("HOUSE_RENT_ID")]
    public int? HouseRentId { get; set; }

    [Column("HOUSE_RENT_DESCRIPTION")]
    [StringLength(50)]
    public string HouseRentDescription { get; set; }

    [Column("DEFINE_CONTRIBUTION_DESCRIPTION")]
    [StringLength(50)]
    public string DefineContributionDescription { get; set; }

    [Column("GROSSPAY_DESCRIPTION")]
    [StringLength(50)]
    public string GrosspayDescription { get; set; }

    [Column("RELIEF_DESCRIPTION")]
    [StringLength(50)]
    public string ReliefDescription { get; set; }

    [Column("TAXABLEPAY_DESCRIPTION")]
    [StringLength(50)]
    public string TaxablepayDescription { get; set; }

    [Column("CARRY_ROUNDING")]
    public bool? CarryRounding { get; set; }

    [Column("DISPLAY_ROUNDING")]
    public bool? DisplayRounding { get; set; }

    [Column("VEHICLE_BENEFIT_PERCENTAGE")]
    public double? VehicleBenefitPercentage { get; set; }

    [Column("EDIT_LEAVE")]
    public bool? EditLeave { get; set; }

    [Column("IGNOREVALUEOFQUARTERS")]
    public bool? Ignorevalueofquarters { get; set; }

    [Column("LOANBENEFIT_ID")]
    public int? LoanbenefitId { get; set; }

    [Column("LoanBenefit_Desc")]
    [StringLength(50)]
    public string LoanBenefitDesc { get; set; }

    [Column("REJECTSALDEDUCTIONS")]
    public bool? Rejectsaldeductions { get; set; }
}