// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblOverDrawn")]
public partial class TblOverDrawn
{
    [Key]
    [Column("Employee_Id")]
    public int? EmployeeId { get; set; }

    [Column("ODescription")]
    [StringLength(50)]
    public string Odescription { get; set; }

    [Column("OverDrawn_Amount", TypeName = "money")]
    public decimal? OverDrawnAmount { get; set; }

    [Column("Period_Month")]
    public int? PeriodMonth { get; set; }

    [Column("Period_Year")]
    public int? PeriodYear { get; set; }
}