// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblOPeningBalances")]
public partial class TblOpeningBalance
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EMPLOYEE_ID")]
    public int EmployeeId { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int PayrollcodeId { get; set; }

    [Column("OPENING_BALANCE", TypeName = "money")]
    public decimal OpeningBalance { get; set; }

    [Column("PERIOD_MONTH")]
    public int PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int PeriodYear { get; set; }
}