// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblPayRollGrades")]
public partial class TblPayRollGrade
{
    [StringLength(50)]
    public string Grade { get; set; }

    [StringLength(50)]
    public string Description { get; set; }
    [Key]
    [Column(TypeName = "money")]
    public decimal? BasicPayFrom { get; set; }

    [Column(TypeName = "money")]
    public decimal? BasicPayTo { get; set; }
}