// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPayrollTransactions")]
public partial class TblPayrollTransaction
{
    [Key]
    [Column("PTRANSACTION_ID")]
    public int PtransactionId { get; set; }

    [Column("PAYPOINT_ID")]
    public int? PaypointId { get; set; }

    [Column("GRADE_ID")]
    public int? GradeId { get; set; }

    [Column("DESIGNATION_ID")]
    public int? DesignationId { get; set; }

    [Column("CSTRUCTURE_ID")]
    public int? CstructureId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("EMPLOYEE")]
    public bool Employee { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("PTRANSACTION_PERIOD")]
    public int? PtransactionPeriod { get; set; }

    [Column("PTRANSACTION_YEAR")]
    public int? PtransactionYear { get; set; }

    [Column("PTRANSACTION_DATE", TypeName = "smalldatetime")]
    public DateTime? PtransactionDate { get; set; }

    [Column("PTRANSACTION_TYPE")]
    [StringLength(50)]
    public string PtransactionType { get; set; }

    [Column("PTRANSACTION_GROUP")]
    [StringLength(50)]
    public string PtransactionGroup { get; set; }

    [Column("PTRANSACTION_DESCRIPTION")]
    [StringLength(50)]
    public string PtransactionDescription { get; set; }

    [Column("PTRANSACTION_AMOUNT")]
    public double? PtransactionAmount { get; set; }

    [Column("PTRANSACTION_RAMOUNT")]
    public double? PtransactionRamount { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("PROCESSED")]
    public bool Processed { get; set; }
}