// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPayslip")]
public partial class TblPayslip
{
    [Key]
    [Column("PAYSLIP_ID")]
    public int PayslipId { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("GRADE_ID")]
    public int? GradeId { get; set; }

    [Column("DESIGNATION_ID")]
    public int? DesignationId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("CSTRUCTURE_ID")]
    public int? CstructureId { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("PTYPE")]
    [StringLength(50)]
    public string Ptype { get; set; }

    [Column("PGROUP")]
    [StringLength(50)]
    public string Pgroup { get; set; }

    [Column("PDESCRIPTION")]
    [StringLength(50)]
    public string Pdescription { get; set; }

    [Column("CONVERSION_RATE")]
    public double? ConversionRate { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("ROUNDED_AMOUNT")]
    public double? RoundedAmount { get; set; }

    [Column("CONVERTED_AMOUNT")]
    public double? ConvertedAmount { get; set; }

    [Column("PRINTED")]
    public bool Printed { get; set; }
}