// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPasswordRule")]
public partial class TblPasswordRule
{
    [Key]
    [Column("RULE_ID")]
    public int RuleId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("CHANGE_AFTER")]
    public int? ChangeAfter { get; set; }

    [Column("MINIMUM_LENGTH")]
    public int? MinimumLength { get; set; }

    [Column("PASSWORD_HISTORY")]
    public int? PasswordHistory { get; set; }

    [Column("LOCKOUT_THRESHOLD")]
    public int? LockoutThreshold { get; set; }

    [Column("LOCK_OUTTIME")]
    public int? LockOuttime { get; set; }
}