// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPayeUganda")]
public partial class TblPayeUgandum
{
    [Key]
    [Column("PAYE_ID")]
    public int PayeId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("PAYE_TIER")]
    public double? PayeTier { get; set; }

    [Column("RATE")]
    public double? Rate { get; set; }
}