// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPayrollCodeRanges")]
public partial class TblPayrollCodeRange
{
    [Key]
    public int PayrollcodeRangeId { get; set; }

    public int PayrollcodeId { get; set; }

    [Column(TypeName = "money")]
    public decimal UpperLimit { get; set; }

    [Column(TypeName = "money")]
    public decimal LowerLimit { get; set; }

    [Column(TypeName = "money")]
    public decimal Retainer { get; set; }

    public bool ExcludeRetainer { get; set; }

    public int CommissionMode { get; set; }

    [Column(TypeName = "money")]
    public decimal? Commission { get; set; }
}