// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblPayeTanzania")]
public partial class TblPayeTanzanium
{
    [Column("PAYE_ID")]
    public int PayeId { get; set; }

    [Column("PAYE_TIER", TypeName = "money")]
    public decimal PayeTier { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal Amount { get; set; }

    [Column("RATE", TypeName = "money")]
    public decimal Rate { get; set; }

    [Column("OVER", TypeName = "money")]
    public decimal Over { get; set; }

    [Column("Company_ID")]
    public int? CompanyId { get; set; }
}