// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPeriods")]
public partial class TblPeriod
{
    [Key]
    [Column("PeriodID")]
    public int PeriodId { get; set; }

    [Column("CompanyID")]
    public int? CompanyId { get; set; }

    [StringLength(50)]
    public string PeriodMonth { get; set; }

    public int? PeriodYear { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? OpenDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? CloseDate { get; set; }

    [Column("OpenEmpID")]
    public int? OpenEmpId { get; set; }

    [Column("CloseEmpID")]
    public int? CloseEmpId { get; set; }

    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? LastPostedDate { get; set; }
}