// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblProtime")]
public partial class TblProtime
{
    [Key]
    [Column("PROTIMEID")]
    public int Protimeid { get; set; }

    [Column("PAYROLLCODENAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Payrollcodename { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("HOURS", TypeName = "numeric(18, 0)")]
    public decimal? Hours { get; set; }

    [Column("EMPLOYEECODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Employeecode { get; set; }

    [Column("PERIOD_DAY", TypeName = "numeric(18, 0)")]
    public decimal? PeriodDay { get; set; }

    [Column("PERIOD_MONTH", TypeName = "numeric(18, 0)")]
    public decimal? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR", TypeName = "numeric(18, 0)")]
    public decimal? PeriodYear { get; set; }

    [Column("PROCESSED")]
    public bool? Processed { get; set; }

    [Column("POST_DAY", TypeName = "numeric(18, 0)")]
    public decimal? PostDay { get; set; }

    [Column("POST_MONTH", TypeName = "numeric(18, 0)")]
    public decimal? PostMonth { get; set; }

    [Column("POST_YEAR", TypeName = "numeric(18, 0)")]
    public decimal? PostYear { get; set; }

    [Column("DAILYRATE", TypeName = "money")]
    public decimal? Dailyrate { get; set; }

    [Column("INCREMENTFACTOR")]
    public double? Incrementfactor { get; set; }
}