// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPayrollCode")]
public partial class TblPayrollCode
{
    [Key]
    [Column("PAYROLLCODE_ID")]
    public int PayrollcodeId { get; set; }

    [Column("COMPANY_ID")]
    public double? CompanyId { get; set; }

    [Column("PAYROLLCODE_CODE")]
    [StringLength(255)]
    public string PayrollcodeCode { get; set; }

    [Column("PAYROLLCODE_NAME")]
    [StringLength(255)]
    public string PayrollcodeName { get; set; }

    [Column("NO_BALANCE")]
    public double? NoBalance { get; set; }

    [Column("REDUCING")]
    public double? Reducing { get; set; }

    [Column("INCREASING")]
    public double? Increasing { get; set; }

    [Column("TAXABLE")]
    public bool? Taxable { get; set; }

    [Column("PAYMENT")]
    public bool? Payment { get; set; }

    [Column("DEDUCTION")]
    public bool? Deduction { get; set; }

    [Column("ISSTATEMENT")]
    public bool? Isstatement { get; set; }

    [Column("RESULTCODE")]
    [StringLength(255)]
    public string Resultcode { get; set; }

    [Column("ISLOAN")]
    public bool? Isloan { get; set; }

    [Column("ISPENSION")]
    public bool? Ispension { get; set; }

    [Column("CASH_BASED")]
    public bool? CashBased { get; set; }

    [Column("FIXED")]
    public bool? Fixed { get; set; }

    [Column("VARIED")]
    public bool? Varied { get; set; }

    [Column("ISAMOUNT")]
    public bool? Isamount { get; set; }

    [Column("PAYROLLCODE_FORMULA")]
    [StringLength(255)]
    public string PayrollcodeFormula { get; set; }

    [Column("LIMIT", TypeName = "money")]
    public decimal? Limit { get; set; }

    [Column("ROUNDING")]
    [StringLength(255)]
    public string Rounding { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }

    [Column("RECOVEREDFROM")]
    [StringLength(255)]
    public string Recoveredfrom { get; set; }

    public double? Factor { get; set; }

    [Column("SYSTEMCODE_ID")]
    public int? SystemcodeId { get; set; }

    [Column("P9COLUMN")]
    public int? P9column { get; set; }

    [Column("INTEREST_RATE")]
    public double? InterestRate { get; set; }

    [Column("INTEREST_MODE")]
    public int? InterestMode { get; set; }

    [Column("FRINGE_BENEFIT")]
    [StringLength(10)]
    [Unicode(false)]
    public string FringeBenefit { get; set; }

    [Column("MAX_APPLICANTS")]
    public int? MaxApplicants { get; set; }

    [Column("RESULTCODE_ID")]
    public int? ResultcodeId { get; set; }

    [Column("PENSIONEMPLOYEEPERC", TypeName = "money")]
    public decimal Pensionemployeeperc { get; set; }

    [Column("PENSIONEMPLOYERPERC", TypeName = "money")]
    public decimal Pensionemployerperc { get; set; }

    [Column("EXEMPTNSSF")]
    public bool Exemptnssf { get; set; }

    [Column("NSSFINCLUSIVE")]
    public bool Nssfinclusive { get; set; }

    public bool? UseRange { get; set; }

    public bool? IsCummulative { get; set; }

    public int? Separated { get; set; }

    public bool? ChargeEmployer { get; set; }

    [Column(TypeName = "money")]
    public decimal? EmployerPerc { get; set; }
}