// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPayroll")]
public partial class TblPayroll
{
    [Key]
    [Column("PAYROLL_ID")]
    public int PayrollId { get; set; }

    [Column("PAYROLL_CODE")]
    [StringLength(50)]
    public string PayrollCode { get; set; }

    [Column("PAYROLL_NAME")]
    [StringLength(50)]
    public string PayrollName { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("DATE_ENTERED", TypeName = "smalldatetime")]
    public DateTime? DateEntered { get; set; }

    [Column("ROUNDING")]
    public int? Rounding { get; set; }

    [Column("ISCasual")]
    public bool? Iscasual { get; set; }

    public bool? PostDailyValues { get; set; }
}