// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPostingFormats")]
public partial class TblPostingFormat
{
    [Key]
    public int PostingFormatId { get; set; }

    [StringLength(200)]
    public string PostingFormatName { get; set; }
}