// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblPeriodTransactions")]
public partial class TblPeriodTransaction
{
    [Key]
    [Column("PAYSLIP_ID")]
    public long PayslipId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("DEPARTMENT_ID")]
    public int? DepartmentId { get; set; }

    [Column("SUBDEPARTMENT_ID")]
    public int? SubdepartmentId { get; set; }

    [Column("SECTION_ID")]
    public int? SectionId { get; set; }

    [Column("GRADE_ID")]
    public int? GradeId { get; set; }

    [Column("DESIGNATION_ID")]
    public int? DesignationId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("PGROUP")]
    [StringLength(50)]
    public string Pgroup { get; set; }

    [Column("PDESCRIPTION")]
    [StringLength(250)]
    public string Pdescription { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("CONVERSION_RATE")]
    public double? ConversionRate { get; set; }

    [Column("CONVERTED_AMOUNT")]
    public double? ConvertedAmount { get; set; }

    [Column("GROUP_ORDER")]
    public int? GroupOrder { get; set; }

    [Column("SUBGROUP_ORDER")]
    public short? SubgroupOrder { get; set; }

    [Column("MESSAGE")]
    [StringLength(250)]
    public string Message { get; set; }

    [Column("BALANCE")]
    public int? Balance { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("PAYPOINT_ID")]
    public int? PaypointId { get; set; }

    public int? FormatId { get; set; }

    [Column(TypeName = "money")]
    public decimal? SourceAmount { get; set; }
}