// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblRelief")]
public partial class TblRelief
{
    [Key]
    [Column("RELIEF_ID")]
    public int ReliefId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("RELIEF_NAME")]
    [StringLength(50)]
    public string ReliefName { get; set; }

    [Column("RELIEF_VALUE")]
    public double? ReliefValue { get; set; }

    [Column("RATE_BASED")]
    public bool RateBased { get; set; }
}