// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblServices")]
public partial class TblService
{
    [Key]
    [Column("Services_Id")]
    public long ServicesId { get; set; }

    [Column("Water_Urban", TypeName = "money")]
    public decimal? WaterUrban { get; set; }

    [Column("Water_Rural", TypeName = "money")]
    public decimal? WaterRural { get; set; }

    [Column("Telephone_Urban", TypeName = "numeric(18, 0)")]
    public decimal? TelephoneUrban { get; set; }

    [Column("Telephone_Rural", TypeName = "numeric(18, 0)")]
    public decimal? TelephoneRural { get; set; }

    [Column("Electricity_Urban", TypeName = "money")]
    public decimal? ElectricityUrban { get; set; }

    [Column("Electricity_Rural", TypeName = "money")]
    public decimal? ElectricityRural { get; set; }

    [Column("Furniture_Urban", TypeName = "numeric(18, 0)")]
    public decimal? FurnitureUrban { get; set; }

    [Column("Furniture_Rural", TypeName = "numeric(18, 0)")]
    public decimal? FurnitureRural { get; set; }

    [Column("Radio_Urban", TypeName = "money")]
    public decimal? RadioUrban { get; set; }

    [Column("Radio_Rural", TypeName = "money")]
    public decimal? RadioRural { get; set; }
}