// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblSystem")]
public partial class TblSystem
{
    [Key]
    [Column("System_ID")]
    public int SystemId { get; set; }

    [Column("System_Name")]
    [StringLength(50)]
    public string SystemName { get; set; }

    [Column("System_Caption")]
    [StringLength(50)]
    public string SystemCaption { get; set; }

    [Column("System_Description", TypeName = "ntext")]
    public string SystemDescription { get; set; }

    public bool? Blocked { get; set; }
}