// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblServiceEmployee")]
public partial class TblServiceEmployee
{
    [Key]
    [Column("EMPLOYEESERVICE_ID")]
    public int EmployeeserviceId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("SERVICE_ID")]
    public int? ServiceId { get; set; }

    [Column("SECTION_NAME")]
    [StringLength(250)]
    public string SectionName { get; set; }

    [Column("EMPLOYEENAME")]
    [StringLength(250)]
    public string Employeename { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("AMOUNT_COLLECTED")]
    public double? AmountCollected { get; set; }

    [Column("COLLECTED")]
    public bool? Collected { get; set; }

    [Column("ALERT_DATE", TypeName = "smalldatetime")]
    public DateTime? AlertDate { get; set; }

    [Column("PROCESSED")]
    public bool Processed { get; set; }

    [Column("TOTAL_DEDUCTIONS", TypeName = "money")]
    public decimal? TotalDeductions { get; set; }
}