// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblServiceChargeDeductions")]
public partial class TblServiceChargeDeduction
{
    [Key]
    [Column("SERVICECHARGE_ID")]
    public int ServicechargeId { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("DATE_TRANSACTION", TypeName = "smalldatetime")]
    public DateTime? DateTransaction { get; set; }

    [Column("recovered")]
    public bool Recovered { get; set; }

    [Column("SERVICE_ID")]
    public int ServiceId { get; set; }
}