// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblStatementCodes")]
public partial class TblStatementCode
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("PAYROLLCODEID")]
    public int? Payrollcodeid { get; set; }

    [Column("RESULTCODE_ID")]
    public int? ResultcodeId { get; set; }

    [Column("RESULTCODE")]
    [StringLength(50)]
    public string Resultcode { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }
}