// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblSystemErrors")]
public partial class TblSystemError
{
    [Column("Error_Id")]
    public int ErrorId { get; set; }

    [Column("Error_Date", TypeName = "datetime")]
    public DateTime ErrorDate { get; set; }

    [Column("Error_Time", TypeName = "datetime")]
    public DateTime ErrorTime { get; set; }

    [Column("Error_Number")]
    [StringLength(50)]
    public string ErrorNumber { get; set; }

    [Column("Error_Source")]
    [StringLength(2000)]
    public string ErrorSource { get; set; }

    [Column("Error_Module")]
    [StringLength(2000)]
    public string ErrorModule { get; set; }

    [Column("Error_Machine")]
    [StringLength(100)]
    public string ErrorMachine { get; set; }

    [Column("Error_Description")]
    [StringLength(4000)]
    public string ErrorDescription { get; set; }

    [Column("Error_UDescription")]
    [StringLength(4000)]
    public string ErrorUdescription { get; set; }

    [Column("Error_Emailed")]
    public bool? ErrorEmailed { get; set; }

    [Column("Error_Printed")]
    public bool? ErrorPrinted { get; set; }

    [Column("Error_Cleared")]
    public bool? ErrorCleared { get; set; }
}