// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblServiceCharge")]
public partial class TblServiceCharge
{
    [Key]
    [Column("SERVICE_ID")]
    public int ServiceId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("CURRENCY_ID")]
    public int? CurrencyId { get; set; }

    [Column("SERVICE_AMOUNT")]
    public double? ServiceAmount { get; set; }

    [Column("AMOUNT_UTILISED")]
    public double? AmountUtilised { get; set; }

    [Column("SERVICE_RATE")]
    public double? ServiceRate { get; set; }

    [Column("PERIOD")]
    public int? Period { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("PROCESSED")]
    public bool? Processed { get; set; }

    [Column("payrollcode_id")]
    public int? PayrollcodeId { get; set; }
}