// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblSettings")]
public partial class TblSetting
{
    public int? SettingsType { get; set; }

    [StringLength(50)]
    public string SettingsName { get; set; }

    [StringLength(200)]
    public string SettingsValue { get; set; }

    public int? CoCode { get; set; }
    [Key]
    [Column("YearID")]
    public int? YearId { get; set; }

    [Column("UserID")]
    public int? UserId { get; set; }
}