// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblTransaction")]
public partial class TblTransaction
{
    [Key]
    [Column("TRANS_ID")]
    public int TransId { get; set; }

    [Column("TRANS_DATE", TypeName = "smalldatetime")]
    public DateTime? TransDate { get; set; }

    [Column("EMPLOYEE_ID")]
    public int? EmployeeId { get; set; }

    [Column("TRANS_TYPE")]
    [StringLength(50)]
    public string TransType { get; set; }

    [Column("AMOUNT")]
    public double? Amount { get; set; }

    [Column("THEORETICAL_AMOUNT")]
    public double? TheoreticalAmount { get; set; }
}