// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblTransactionType")]
public partial class TblTransactionType
{
    [Key]
    [Column("TTYPE_ID")]
    public int TtypeId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("TTYPE_CODE")]
    [StringLength(50)]
    public string TtypeCode { get; set; }

    [Column("TTYPE_NAME")]
    [StringLength(50)]
    public string TtypeName { get; set; }

    [Column("BENEFIT")]
    public bool Benefit { get; set; }

    [Column("DEDUCTION")]
    public bool Deduction { get; set; }
}