// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblUserGroup1")]
public partial class TblUserGroup1
{
    [Key]   
    [Column("GROUP_ID")]
    public int GroupId { get; set; }

    [Column("COMPANY_ID")]
    public int? CompanyId { get; set; }

    [Column("GROUP_CODE")]
    [StringLength(50)]
    public string GroupCode { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(50)]
    public string GroupName { get; set; }
}