// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblUnusedRelief")]
public partial class TblUnusedRelief
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("EMPID")]
    public int? Empid { get; set; }

    [Column("PAYROLLCODE_ID")]
    public int? PayrollcodeId { get; set; }

    [Column("PERIOD_MONTH")]
    public int? PeriodMonth { get; set; }

    [Column("PERIOD_YEAR")]
    public int? PeriodYear { get; set; }

    [Column("AMOUNT", TypeName = "money")]
    public decimal? Amount { get; set; }
}