// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Table("tblUserLog")]
public partial class TblUserLog
{
    [Key]
    [Column("LOG_ID")]
    public int LogId { get; set; }

    [Column("USER_ID")]
    public int? UserId { get; set; }

    [Column("LOG_DATE", TypeName = "smalldatetime")]
    public DateTime? LogDate { get; set; }

    [Column("LOG_TIME", TypeName = "smalldatetime")]
    public DateTime? LogTime { get; set; }

    [Column("LOG_TYPE")]
    [StringLength(50)]
    public string LogType { get; set; }

    [Column("LOG_DESCRIPTION", TypeName = "ntext")]
    public string LogDescription { get; set; }
}