// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("tblUserGroup")]
public partial class TblUserGroup
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("GROUP_CODE")]
    [StringLength(50)]
    public string GroupCode { get; set; }

    [Column("GROUP_NAME")]
    [StringLength(50)]
    public string GroupName { get; set; }

    [StringLength(50)]
    public string SubSystem { get; set; }
}