// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("tblVariance")]
public partial class TblVariance
{
    [Column("Employee_id")]
    public int? EmployeeId { get; set; }

    [Column("PayrollCode_id")]
    public int? PayrollCodeId { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Jan { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Feb { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? JanFeb { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Mar { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? FebMar { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Apr { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? MarApr { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? May { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? AprMay { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Jun { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? MayJun { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Jul { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? JunJul { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Aug { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? JulAug { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Sep { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? AugSep { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Oct { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? SepOct { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Nov { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? OctNov { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Dec { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? NovDec { get; set; }

    [Column(TypeName = "numeric(18, 0)")]
    public decimal? Year { get; set; }
}