// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("u_audittrail")]
public partial class UAudittrail
{
    [Key]
    [Column("logid")]
    public int? Logid { get; set; }

    [Column("detailtime", TypeName = "smalldatetime")]
    public DateTime? Detailtime { get; set; }

    [Column("usercode")]
    [StringLength(100)]
    [Unicode(false)]
    public string Usercode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string ProgramName { get; set; }

    [Column("beforeimage")]
    [StringLength(100)]
    [Unicode(false)]
    public string Beforeimage { get; set; }

    [Column("afterimage")]
    [StringLength(100)]
    [Unicode(false)]
    public string Afterimage { get; set; }
}