// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("u_logins")]
public partial class ULogin
{
    [Key]   
    [Column("logid")]
    public int Logid { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LoginDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? LoginTime { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string UserCode { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LogOutDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? LogOutTime { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string LoggedOut { get; set; }

    [StringLength(50)]
    public string MachineName { get; set; }
}