// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("u_payrollAccess")]
public partial class UPayrollAccess
{
    [StringLength(100)]
    public string UserCode { get; set; }

    [StringLength(100)]
    public string RoleCode { get; set; }

    public int? PayrollId { get; set; }
}