// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("u_policysetting")]
public partial class UPolicysetting
{
    [Key]
    [Column("pwdminage")]
    public int? Pwdminage { get; set; }

    [Column("pwdmaxage")]
    public int? Pwdmaxage { get; set; }

    [Column("pwdmaxlength")]
    public int? Pwdmaxlength { get; set; }

    [Column("pwdminlength")]
    public int? Pwdminlength { get; set; }

    [Column("pwdcomplex")]
    public int? Pwdcomplex { get; set; }

    [Column("pwdhistory")]
    public int? Pwdhistory { get; set; }
}