// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("u_roles")]
public partial class URole
{
    [Column("rolename")]
    [StringLength(100)]
    [Unicode(false)]
    public string Rolename { get; set; }

    [Column("rolecomments")]
    [StringLength(100)]
    [Unicode(false)]
    public string Rolecomments { get; set; }

    [Column("rolecode")]
    [StringLength(100)]
    [Unicode(false)]
    public string Rolecode { get; set; }

    [Column("roleid")]
    public int Roleid { get; set; }
}