// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("u_userpwdhists")]
public partial class UUserpwdhist
{
    [Column("usercode")]
    [StringLength(100)]
    [Unicode(false)]
    public string Usercode { get; set; }

    [Column("userpwd")]
    [StringLength(100)]
    [Unicode(false)]
    public string Userpwd { get; set; }
}