// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

//[Keyless]
[Table("u_user")]
public partial class UUser
{
    [Key]
    [Column("userid")]
    public int? Userid { get; set; }

    [Column("usercode")]
    [StringLength(100)]
    [Unicode(false)]
    public string Usercode { get; set; }

    [Column("username")]
    [StringLength(100)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("usertitle")]
    [StringLength(100)]
    [Unicode(false)]
    public string Usertitle { get; set; }

    [Column("usersurname")]
    [StringLength(100)]
    [Unicode(false)]
    public string Usersurname { get; set; }

    [Column("userfirstname")]
    [StringLength(100)]
    [Unicode(false)]
    public string Userfirstname { get; set; }

    [Column("userothername")]
    [StringLength(100)]
    [Unicode(false)]
    public string Userothername { get; set; }

    [Column("userpwddate", TypeName = "smalldatetime")]
    public DateTime? Userpwddate { get; set; }

    [Column("userpassword")]
    [StringLength(100)]
    [Unicode(false)]
    public string Userpassword { get; set; }
}