// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("u_users")]
public partial class UUser1
{
    [Column("rolecode")]
    [StringLength(50)]
    [Unicode(false)]
    public string Rolecode { get; set; }

    [Column("usercode")]
    [StringLength(50)]
    [Unicode(false)]
    public string Usercode { get; set; }

    [Column("username")]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("userusername")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userusername { get; set; }

    [Column("userpwd")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userpwd { get; set; }

    [Column("userpwddate", TypeName = "smalldatetime")]
    public DateTime? Userpwddate { get; set; }

    [Column("userlocked")]
    public int? Userlocked { get; set; }

    public int? IsDeleted { get; set; }
}