// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OntimePayrollAPI.Models;

[Keyless]
[Table("YrsGroup")]
public partial class YrsGroup
{
    [Column("ID")]
    public long Id { get; set; }

    [Column("YFrom")]
    public int? Yfrom { get; set; }

    [Column("YTo")]
    public int? Yto { get; set; }
}